/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import javax.swing.JFrame;
import javax.swing.SwingUtilities;




/**
 *
 * @author ASUS
 */
public class AdminFunktionerForm extends javax.swing.JPanel {
    private String epost;
    private String isAdmin;

    /**
     * Creates new form AdminFunktionerForm
     */
    public AdminFunktionerForm(String epost,String isAdmin) {
        initComponents();
        this.epost = epost;
        this.isAdmin = isAdmin;
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBefordaAgent = new javax.swing.JButton();
        btnHanteraChef = new javax.swing.JButton();

        btnBefordaAgent.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnBefordaAgent.setText("Befordra Agent");
        btnBefordaAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBefordaAgentActionPerformed(evt);
            }
        });

        btnHanteraChef.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnHanteraChef.setText("Hantera chefer");
        btnHanteraChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHanteraChefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnHanteraChef)
                    .addComponent(btnBefordaAgent))
                .addContainerGap(334, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(btnBefordaAgent)
                .addGap(38, 38, 38)
                .addComponent(btnHanteraChef)
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBefordaAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBefordaAgentActionPerformed
         JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(AdminFunktionerForm.this);
                frame.setContentPane(new BefordraAgentForm(epost,isAdmin));
                frame.revalidate();
                frame.setTitle("Befordra Agent");
                frame.repaint();
    }//GEN-LAST:event_btnBefordaAgentActionPerformed

    private void btnHanteraChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHanteraChefActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(AdminFunktionerForm.this);
                frame.setContentPane(new HanteraCheferForm(epost,isAdmin));
                frame.revalidate();
                frame.setTitle("Hantera chefer");
                frame.repaint();
    }//GEN-LAST:event_btnHanteraChefActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBefordaAgent;
    private javax.swing.JButton btnHanteraChef;
    // End of variables declaration//GEN-END:variables
}
