
package mib.p;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;


public class AndraInfoOmAgent extends javax.swing.JPanel {
    private static InfDB idb;
    private String epost;
    private String isAdmin;

    /**
     * Creates new form AndraInfoOmAgent
     */
    public AndraInfoOmAgent(String epost, String isAdmin) {
        initComponents();
        this.epost = epost;
        this.isAdmin = isAdmin;
        jPaneInfoAgent.setVisible(true);
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUppdater = new javax.swing.JButton();
        jPaneInfoAgent = new javax.swing.JPanel();
        lblAnstallningsDatum = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        lblTelefon = new javax.swing.JLabel();
        txtAnstallningsdatum = new javax.swing.JTextField();
        lblAdminstrator = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        lblNamn = new javax.swing.JLabel();
        txtOmrade = new javax.swing.JTextField();
        txtLosenOrd = new javax.swing.JTextField();
        lblLosenOrd = new javax.swing.JLabel();
        lblOmrade = new javax.swing.JLabel();
        lblNuvarandeInfo = new javax.swing.JLabel();
        txtAndraNamn = new javax.swing.JTextField();
        txtAndraTelefon = new javax.swing.JTextField();
        txtAdministrator = new javax.swing.JTextField();
        txtAndraLosenOrd = new javax.swing.JTextField();
        lblNyInfo = new javax.swing.JLabel();
        jComboValjAdministrator = new javax.swing.JComboBox<>();
        jComboValjOmrade = new javax.swing.JComboBox<>();
        txtAndraAnstallningsdatum = new javax.swing.JTextField();
        btnRensa = new javax.swing.JButton();
        lblAngeAgentID = new javax.swing.JLabel();
        txtAgentID = new javax.swing.JTextField();
        btnSok = new javax.swing.JButton();
        btnMinSida = new javax.swing.JButton();
        btnAdminSida = new javax.swing.JButton();

        btnUppdater.setText("Uppdatera ");
        btnUppdater.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUppdaterActionPerformed(evt);
            }
        });

        jPaneInfoAgent.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));

        lblAnstallningsDatum.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblAnstallningsDatum.setText("Anställningsdatum:");

        lblTelefon.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblTelefon.setText("Telefon:");

        lblAdminstrator.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblAdminstrator.setText("Administratör:");

        lblNamn.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblNamn.setText("Namn:");

        lblLosenOrd.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblLosenOrd.setText("Lösenord:");

        lblOmrade.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblOmrade.setText("Område:");

        lblNuvarandeInfo.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblNuvarandeInfo.setText("Nuvarande info");

        lblNyInfo.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblNyInfo.setText("Ny info");

        jComboValjAdministrator.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj Administratör", "J", "N" }));
        jComboValjAdministrator.setToolTipText("");

        jComboValjOmrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj Område", "Svealand", "Götaland", "Norrland" }));

        javax.swing.GroupLayout jPaneInfoAgentLayout = new javax.swing.GroupLayout(jPaneInfoAgent);
        jPaneInfoAgent.setLayout(jPaneInfoAgentLayout);
        jPaneInfoAgentLayout.setHorizontalGroup(
            jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneInfoAgentLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblTelefon)
                .addGap(388, 388, 388))
            .addGroup(jPaneInfoAgentLayout.createSequentialGroup()
                .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneInfoAgentLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAdminstrator)
                            .addComponent(lblNamn)
                            .addComponent(lblOmrade)
                            .addComponent(lblLosenOrd)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneInfoAgentLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblAnstallningsDatum)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtNamn)
                        .addComponent(txtAnstallningsdatum)
                        .addComponent(txtTelefon)
                        .addComponent(txtAdministrator)
                        .addComponent(txtOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtLosenOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblNuvarandeInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtAndraTelefon)
                    .addComponent(txtAndraLosenOrd)
                    .addGroup(jPaneInfoAgentLayout.createSequentialGroup()
                        .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNyInfo)
                            .addComponent(txtAndraNamn)
                            .addComponent(jComboValjAdministrator, 0, 144, Short.MAX_VALUE)
                            .addComponent(jComboValjOmrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAndraAnstallningsdatum))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPaneInfoAgentLayout.setVerticalGroup(
            jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneInfoAgentLayout.createSequentialGroup()
                .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuvarandeInfo)
                    .addComponent(lblNyInfo))
                .addGap(6, 6, 6)
                .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamn)
                    .addComponent(txtAndraNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnstallningsDatum)
                    .addComponent(txtAndraAnstallningsdatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefon)
                    .addComponent(txtAndraTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAdminstrator)
                    .addComponent(txtAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboValjAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOmrade)
                    .addComponent(jComboValjOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneInfoAgentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLosenOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLosenOrd)
                    .addComponent(txtAndraLosenOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnRensa.setText("Rensa");
        btnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensaActionPerformed(evt);
            }
        });

        lblAngeAgentID.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAngeAgentID.setText("Ange Agent ID:");

        btnSok.setText("Sök");
        btnSok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokActionPerformed(evt);
            }
        });

        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        btnAdminSida.setText("Adminsida");
        btnAdminSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminSidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(lblAngeAgentID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnSok))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPaneInfoAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdminSida)
                .addGap(59, 59, 59)
                .addComponent(btnUppdater)
                .addGap(30, 30, 30)
                .addComponent(btnRensa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinSida)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAngeAgentID)
                    .addComponent(txtAgentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSok))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPaneInfoAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUppdater)
                    .addComponent(btnRensa)
                    .addComponent(btnMinSida)
                    .addComponent(btnAdminSida))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokActionPerformed
        // Omvandlar inmatningen av agent id till int version från String.
        String agentIDString = txtAgentID.getText();
        int agentIDInt = Integer.parseInt(agentIDString);
        
        try {
            
            // Nuvarande namn
            String namn = idb.fetchSingle("SELECT Namn FROM mibdb.agent WHERE Agent_ID = "+agentIDInt+";");
            txtNamn.setText(namn);
            
            // Nuvarande anställningsdatum
            String anstallningsdatum = idb.fetchSingle("SELECT Anstallningsdatum FROM mibdb.agent WHERE Agent_ID = "+agentIDInt+";");
            txtAnstallningsdatum.setText(anstallningsdatum);
            
            // Nuvarande telefon 
            String telefon = idb.fetchSingle("SELECT Telefon FROM mibdb.agent WHERE Agent_ID = "+agentIDInt+";");
            txtTelefon.setText(telefon);
            
            // Nuvarande administratör 
            String administrator = idb.fetchSingle("SELECT Administrator FROM mibdb.agent WHERE Agent_ID = "+agentIDInt+";");
            txtAdministrator.setText(administrator);
            
            // Nuvarande Område 
            String omradeString = idb.fetchSingle("SELECT Omrade FROM mibdb.agent WHERE Agent_ID = "+agentIDInt+";");
            // Omvandlade område id till int fron String.
            int omradeInt = Integer.parseInt(omradeString);
            txtOmrade.setText(idb.fetchSingle("SELECT Benamning FROM mibdb.omrade WHERE Omrades_ID ="+omradeInt+";"));
            
            // Nuvarande lösenord
            String losenord = idb.fetchSingle("SELECT Losenord from mibdb.agent WHERE Agent_ID = "+agentIDInt+";");
            txtLosenOrd.setText(losenord);
        
        
        
        } catch (InfException ex) {
            Logger.getLogger(AndraInfoOmAgent.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Något gick fel. Försök igen!");
        }
        
    }//GEN-LAST:event_btnSokActionPerformed
    // Denna knapp rensar allt som finns i textfälten 
    private void btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensaActionPerformed
        txtAdministrator.setText("");
        txtAgentID.setText("");
        txtAndraAnstallningsdatum.setText("");
        txtAndraLosenOrd.setText("");
        txtAndraNamn.setText("");
        txtAndraTelefon.setText("");
        txtAnstallningsdatum.setText("");
        txtLosenOrd.setText("");
        txtNamn.setText("");
        txtOmrade.setText("");
        txtTelefon.setText("");
        txtAgentID.requestFocus();
    }//GEN-LAST:event_btnRensaActionPerformed
    // Denna knapp uppdaterar infon för agenten.
    private void btnUppdaterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUppdaterActionPerformed
        // Omvandlar String versionen av agent id till int typ.
        String agentidString = txtAgentID.getText();
        int agentidInt = Integer.parseInt(agentidString);
        
        // Nya info:
        String nynamn = txtAndraNamn.getText();
        String nyanstallningsdatum = txtAndraAnstallningsdatum.getText();
        String nytelefon = txtAndraTelefon.getText();
        String nyadministrator = (String) jComboValjAdministrator.getSelectedItem();
        String nyomrade = (String) jComboValjOmrade.getSelectedItem();
        String nylosenord = txtAndraLosenOrd.getText();
        try {
            // Här tas och omvandlas omrade id till int typ beroende av det som väljs i combobox.
            String omradeidString = idb.fetchSingle("SELECT Omrades_ID FROM mibdb.omrade WHERE Benamning ='"+nyomrade+"';");
            int omradeidInt = Integer.parseInt(omradeidString);
            
            // Uppdatera infon för agenten.
            idb.update("UPDATE mibdb.agent SET Namn ='"+nynamn+"', Telefon='"+nytelefon+"', Anstallningsdatum ='"+nyanstallningsdatum+"', Administrator ='"+nyadministrator+"', Losenord='"+nylosenord+"', Omrade="+omradeidInt+" WHERE Agent_ID = "+agentidInt+";");
            JOptionPane.showMessageDialog(null, "Informationen ändrades!");
            
        } catch (InfException ex) {
            Logger.getLogger(AndraInfoOmAgent.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Något gick fel. Försök igen!");
        }
               
    }//GEN-LAST:event_btnUppdaterActionPerformed
    // Denna knapp en skickar till AdminSidan. "AdminFunktionerForm".
    private void btnAdminSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminSidaActionPerformed
    JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(AndraInfoOmAgent.this);
        frame.setContentPane(new AdminFunktionerForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Administratörsfunktioner");
        frame.repaint();
    }//GEN-LAST:event_btnAdminSidaActionPerformed
    // Denna knapp skickar en till AgentSidan. "MinSidaAgentForm".
    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(AndraInfoOmAgent.this);
        frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Startsida: Agent");
        frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminSida;
    private javax.swing.JButton btnMinSida;
    private javax.swing.JButton btnRensa;
    private javax.swing.JButton btnSok;
    private javax.swing.JButton btnUppdater;
    private javax.swing.JComboBox<String> jComboValjAdministrator;
    private javax.swing.JComboBox<String> jComboValjOmrade;
    private javax.swing.JPanel jPaneInfoAgent;
    private javax.swing.JLabel lblAdminstrator;
    private javax.swing.JLabel lblAngeAgentID;
    private javax.swing.JLabel lblAnstallningsDatum;
    private javax.swing.JLabel lblLosenOrd;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblNuvarandeInfo;
    private javax.swing.JLabel lblNyInfo;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JTextField txtAdministrator;
    private javax.swing.JTextField txtAgentID;
    private javax.swing.JTextField txtAndraAnstallningsdatum;
    private javax.swing.JTextField txtAndraLosenOrd;
    private javax.swing.JTextField txtAndraNamn;
    private javax.swing.JTextField txtAndraTelefon;
    private javax.swing.JTextField txtAnstallningsdatum;
    private javax.swing.JTextField txtLosenOrd;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtOmrade;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
