/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author ASUS
 */
public class AndraAlienInfoForm extends javax.swing.JPanel {

    private static InfDB idb;
    private String epost;
    private String isAdmin;
    private ValideringsKlass validera = new ValideringsKlass();

    /**
     * Creates new form AlienSokForm
     */
    public AndraAlienInfoForm(String epost, String isAdmin) {
        
       this.isAdmin = isAdmin;
        initComponents();
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        this.epost = epost;

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtAlienIdSok = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        labRas = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        labTelefon = new javax.swing.JLabel();
        txtRas = new javax.swing.JTextField();
        labRegDatum = new javax.swing.JLabel();
        labAnsvAgent = new javax.swing.JLabel();
        txtTelefon = new javax.swing.JTextField();
        txtRegDatum = new javax.swing.JTextField();
        txtAndraAgent = new javax.swing.JTextField();
        labNamn = new javax.swing.JLabel();
        txtPlats = new javax.swing.JTextField();
        txtLosenOrd = new javax.swing.JTextField();
        labLosenOrd = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtAndraNamn = new javax.swing.JTextField();
        txtAndraRas = new javax.swing.JTextField();
        txtAndraTelefon = new javax.swing.JTextField();
        txtAndraRegDatum = new javax.swing.JTextField();
        txtAnsvAgent = new javax.swing.JTextField();
        txtAndraPlats = new javax.swing.JTextField();
        txtAndraLosenOrd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnAndraInfo = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));
        setName(""); // NOI18N

        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Ange Alien ID:");

        jButton1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jButton1.setText("Sök");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));

        labRas.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        labRas.setText("Ras:");

        labTelefon.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        labTelefon.setText("Telefon:");

        labRegDatum.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        labRegDatum.setText("Reg-datum:");

        labAnsvAgent.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        labAnsvAgent.setText("Ansvarig agent:");

        labNamn.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        labNamn.setText("Namn:");

        labLosenOrd.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        labLosenOrd.setText("Lösenord:");

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        jLabel3.setText("Plats:");

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        jLabel1.setText("Nuvarande info");

        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        jLabel4.setText("Ny info");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labRas)
                    .addComponent(labTelefon)
                    .addComponent(labRegDatum)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labAnsvAgent)
                            .addComponent(labNamn)
                            .addComponent(jLabel3)
                            .addComponent(labLosenOrd))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNamn)
                                .addComponent(txtRas)
                                .addComponent(txtTelefon)
                                .addComponent(txtRegDatum)
                                .addComponent(txtAnsvAgent)
                                .addComponent(txtPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtLosenOrd, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAndraRas)
                            .addComponent(txtAndraTelefon)
                            .addComponent(txtAndraAgent, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAndraRegDatum, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAndraPlats)
                            .addComponent(txtAndraLosenOrd)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(txtAndraNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labNamn)
                    .addComponent(txtAndraNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labRas)
                    .addComponent(txtAndraRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labTelefon)
                    .addComponent(txtAndraTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRegDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labRegDatum)
                    .addComponent(txtAndraRegDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAndraAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labAnsvAgent)
                    .addComponent(txtAnsvAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtAndraPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLosenOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labLosenOrd)
                    .addComponent(txtAndraLosenOrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton2.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jButton2.setText("Min sida");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnAndraInfo.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnAndraInfo.setText("Uppdatera");
        btnAndraInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(84, 84, 84)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtAlienIdSok, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 64, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAndraInfo)
                        .addGap(130, 130, 130)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAlienIdSok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAndraInfo)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        alienSok();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(AndraAlienInfoForm.this);
                frame.setContentPane(new MinSidaAgentForm(epost,isAdmin));
                frame.revalidate();
                frame.setTitle("Startsida: Agent");
                frame.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnAndraInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraInfoActionPerformed
       String stringId = txtAlienIdSok.getText();
        int alienID = Integer.parseInt(stringId);
        
        if (ValideringsKlass.validateTextFieldNotEmpty(txtAndraNamn.getText())) {
            andraNamn(alienID);
        }
        if (ValideringsKlass.validateTextFieldNotEmpty(txtAndraTelefon.getText())) {
            andraTelefon(alienID);
        }
        if (ValideringsKlass.validateTextFieldNotEmpty(txtAndraLosenOrd.getText())) {
            andraLosenOrd(alienID);
        }
        if (ValideringsKlass.validateTextFieldNotEmpty(txtAndraRegDatum.getText())) {
            andraRegDatum(alienID);

        }
        if (ValideringsKlass.validateTextFieldNotEmpty(txtAndraRas.getText()) && ValideringsKlass.validateTextFieldNotEmpty(txtRas.getText())) {
            String nuvarandeRas = txtRas.getText();
            String nyRas = txtAndraRas.getText();
            if (nyRas.equals("Worm") || nyRas.equals("Boglodite") || nyRas.equals("Squid")) {
                andraRas(nuvarandeRas, nyRas, Integer.parseInt(txtAlienIdSok.getText()));
            }
        }
        if (ValideringsKlass.validateTextFieldNotEmpty(txtAndraRas.getText()) && !ValideringsKlass.validateTextFieldNotEmpty(txtRas.getText())) {
           String nyRas = txtAndraRas.getText();
           laggTillAlien(nyRas,alienID);
           JOptionPane.showMessageDialog(null, "Rasen uppdaterades. Ny ras: " + nyRas);
        
        }
    }//GEN-LAST:event_btnAndraInfoActionPerformed
    private void setTextFalt(HashMap<String, String> alienInfo) {
        txtNamn.setText(alienInfo.get("Namn"));
        txtRegDatum.setText(alienInfo.get("Registreringsdatum"));
        txtLosenOrd.setText(alienInfo.get("Losenord"));
        
        txtTelefon.setText(alienInfo.get("Telefon"));

    }

    private void setAgent(int alienID) {
        try {
            String agentNamn = idb.fetchSingle("SELECT namn FROM mibdb.agent WHERE Agent_ID IN (SELECT Ansvarig_Agent FROM mibdb.alien WHERE Alien_ID = " + alienID + ")");
            txtAnsvAgent.setText(agentNamn);
        } catch (InfException e) {

        }
    }

    private void setPlats(int alienID) {
        try {
            String platsNamn = idb.fetchSingle("SELECT Benamning FROM mibdb.plats WHERE Plats_ID IN (SELECT Plats FROM mibdb.alien WHERE Alien_ID = " + alienID + ")");
            txtPlats.setText(platsNamn);
        } catch (InfException e) {

        }

    }

    private void setRas(int alienID) {

        String alienIdString = Integer.toString(alienID);

        try {
            ArrayList<String> worm = idb.fetchColumn("SELECT Alien_ID FROM mibdb.worm");
            if (worm.contains(alienIdString)) {
                txtRas.setText("Worm");
            }
        } catch (InfException e) {

        }
        try {
            ArrayList<String> squid = idb.fetchColumn("SELECT Alien_ID FROM mibdb.squid");
            if (squid.contains(alienIdString)) {
                txtRas.setText("Squid");
            }
        } catch (InfException e) {

        }
        try {
            ArrayList<String> boglodite = idb.fetchColumn("SELECT Alien_ID FROM mibdb.boglodite");
            if (boglodite.contains(alienIdString)) {
                txtRas.setText("Boglodite");
            }
        } catch (InfException e) {

        }

    }

    private void alienSok() {
        int alienID;
        if (ValideringsKlass.valideraInt(txtAlienIdSok.getText())) {
            alienID = Integer.parseInt(txtAlienIdSok.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Felaktig inmatning. Ange ett giltigt Alien-ID.");
            return;
        }

        try {
            HashMap<String, String> alienInfo = idb.fetchRow("SELECT * FROM mibdb.alien WHERE Alien_ID = " + alienID + ";");
            setTextFalt(alienInfo);
            setAgent(alienID);
            setPlats(alienID);
            setRas(alienID);

        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Ett fel uppstod vid sökningen av alien.");
        }
    }
    public void andraNamn(int alienID) {

        String nyttNamn = txtAndraNamn.getText();
        try {
            String query = "UPDATE mibdb.alien SET Namn = '" + nyttNamn + "' WHERE Alien_ID = '" + alienID + "'";
            idb.update(query);
            JOptionPane.showMessageDialog(null, "Namnet uppdaterades. Nytt namn: " + nyttNamn);
            txtNamn.setText(nyttNamn);
            txtAndraNamn.setText("");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Ett fel inträffade vid uppdatering av data.");
        }

    }
    
    public void andraTelefon(int alienID) {
        String nyttNummer = txtAndraTelefon.getText();
        if (ValideringsKlass.valideraInt(nyttNummer)) {

            try {
                String query = "UPDATE mibdb.alien SET Telefon = '" + nyttNummer + "' WHERE Alien_ID = '" + alienID + "'";
                idb.update(query);
                JOptionPane.showMessageDialog(null, "Numret uppdaterades. Nytt nummer: " + nyttNummer);
                txtTelefon.setText(nyttNummer);
                txtAndraTelefon.setText("");
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Ett fel inträffade vid uppdatering av data.");
            }
        }
    }
    
    public void andraLosenOrd(int alienID) {
        String nyttLosenOrd = txtAndraLosenOrd.getText();
        {

            try {
                String query = "UPDATE mibdb.alien SET Losenord = '" + nyttLosenOrd + "' WHERE Alien_ID = '" + alienID + "'";
                idb.update(query);
                JOptionPane.showMessageDialog(null, "Lösenordet uppdaterades. Nytt lösenord: " + nyttLosenOrd);
                txtLosenOrd.setText(nyttLosenOrd);
                txtAndraLosenOrd.setText("");
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, "Lösenord för långt. Välj max sex tecken.");
            }
        }

    }
    
     public void andraRegDatum(int alienID) {
        String nyttRegDatum = txtAndraRegDatum.getText();
        if (ValideringsKlass.valideraDatum(nyttRegDatum)) {
            try {
                String query = "UPDATE mibdb.alien SET Registreringsdatum = '" + nyttRegDatum + "' WHERE Alien_ID = '" + alienID + "'";
                idb.update(query);
                JOptionPane.showMessageDialog(null, "Registreringsdatum uppdaterades. Nytt datum: " + nyttRegDatum);
                txtRegDatum.setText(nyttRegDatum);
                txtAndraRegDatum.setText("");
            } catch (InfException e) {
                JOptionPane.showMessageDialog(null, " Ogiltigt registreringsdatum. Ange enligt YYYY-MM-DD");
            }

        } else {
            JOptionPane.showMessageDialog(null, " Ogiltigt registreringsdatum uppdaterades. Ange enligt YYYY-MM-DD");
        }
    }
     
     private void andraRas(String nuvarandeRas, String nyRas, int alienID) {

        taBortAlien(nuvarandeRas, alienID);
        laggTillAlien(nyRas, alienID);
        JOptionPane.showMessageDialog(null, "Rasen uppdaterades. Ny ras: " + nyRas);

        txtRas.setText(nyRas);
        txtAndraRas.setText("");
    }

    public void laggTillAlien(String nyRas, int alienID) {
        try {

            String query = "INSERT INTO mibdb." + nyRas + " (Alien_ID) VALUES (" + alienID + ")";
            idb.insert(query);

            txtRas.setText(nyRas);
            txtAndraRas.setText("");
        } catch (InfException e) {
            System.out.println("Åh nöööh");

        }
    }

    public void taBortAlien(String nuvarandeRas, int alienID) {
        try {

            String query = "DELETE FROM mibdb." + nuvarandeRas + " WHERE Alien_ID = " + alienID;
            idb.delete(query);

        } catch (InfException e) {

        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labAnsvAgent;
    private javax.swing.JLabel labLosenOrd;
    private javax.swing.JLabel labNamn;
    private javax.swing.JLabel labRas;
    private javax.swing.JLabel labRegDatum;
    private javax.swing.JLabel labTelefon;
    private javax.swing.JTextField txtAlienIdSok;
    private javax.swing.JTextField txtAndraAgent;
    private javax.swing.JTextField txtAndraLosenOrd;
    private javax.swing.JTextField txtAndraNamn;
    private javax.swing.JTextField txtAndraPlats;
    private javax.swing.JTextField txtAndraRas;
    private javax.swing.JTextField txtAndraRegDatum;
    private javax.swing.JTextField txtAndraTelefon;
    private javax.swing.JTextField txtAnsvAgent;
    private javax.swing.JTextField txtLosenOrd;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtPlats;
    private javax.swing.JTextField txtRas;
    private javax.swing.JTextField txtRegDatum;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
