/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ASUS
 */
public class AndraLosenOrdAlienForm extends javax.swing.JPanel {
    String epost;
    private static InfDB idb;

    /**
     * Creates new form AndraLosenOrdForm
     */
    public AndraLosenOrdAlienForm(String epost) {
        
        initComponents();
        this.epost= epost;
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAndraLosenord = new javax.swing.JLabel();
        lblNuvarandeLosenord = new javax.swing.JLabel();
        jPasswordNuvarandeLosenord = new javax.swing.JPasswordField();
        lblNyttLosenord = new javax.swing.JLabel();
        jPasswordFieldNytt = new javax.swing.JPasswordField();
        jPasswordFieldUpprepa = new javax.swing.JPasswordField();
        btnMinSida = new javax.swing.JButton();
        lblUpprepaLosenord = new javax.swing.JLabel();
        btnAndra = new javax.swing.JButton();
        btnRensa = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));

        lblAndraLosenord.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblAndraLosenord.setText("Ändra lösenord");

        lblNuvarandeLosenord.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblNuvarandeLosenord.setText("Nuvarande lösenord:");

        lblNyttLosenord.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblNyttLosenord.setText("Ange nytt lösenord:");

        btnMinSida.setBackground(new java.awt.Color(242, 242, 242));
        btnMinSida.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        lblUpprepaLosenord.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblUpprepaLosenord.setText("Upprepa lösenord:");

        btnAndra.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        btnRensa.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnRensa.setText("Rensa");
        btnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(lblAndraLosenord)
                .addContainerGap(220, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNuvarandeLosenord)
                        .addGap(18, 18, 18)
                        .addComponent(jPasswordNuvarandeLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblUpprepaLosenord)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPasswordFieldUpprepa, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnAndra)
                                .addComponent(lblNyttLosenord))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPasswordFieldNytt, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(btnRensa)
                                    .addGap(8, 8, 8))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinSida)
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAndraLosenord)
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNuvarandeLosenord)
                    .addComponent(jPasswordNuvarandeLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldNytt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNyttLosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldUpprepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUpprepaLosenord))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnMinSida)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRensa)
                            .addComponent(btnAndra))
                        .addGap(0, 61, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
    
   JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(AndraLosenOrdAlienForm.this);
                frame.setContentPane(new MinSidaAlienForm(epost));
                frame.revalidate();
                frame.setTitle("Startsida: Alien");
                frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
      String losenord = "";
    try {
        String losenOrdCheck = idb.fetchSingle("SELECT Losenord FROM mibdb.alien WHERE epost = '" + epost + "'");
        losenord = losenOrdCheck;
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
        return; // Avsluta metoden om det uppstår ett fel vid hämtning av lösenordet
    }

    if (jPasswordFieldNytt.getText().equals(jPasswordFieldUpprepa.getText()) && jPasswordNuvarandeLosenord.getText().equals(losenord)) {
        try {
            idb.update("UPDATE mibdb.alien SET Losenord='" + jPasswordFieldNytt.getText() + "' WHERE Epost='" + epost + "';");
            JOptionPane.showMessageDialog(null, "Lösenordet har ändrats.");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel vid uppdatering av lösenordet.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Något gick fel. Försök igen.");
    }
    }//GEN-LAST:event_btnAndraActionPerformed
    // Denna knapp rensar det som står i lösenordfälten och fokuset sätts på nuvarande lösenord fältet.
    private void btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensaActionPerformed
        jPasswordNuvarandeLosenord.setText("");
        jPasswordFieldNytt.setText(""); 
        jPasswordFieldUpprepa.setText(""); 
        jPasswordNuvarandeLosenord.requestFocus();
    }//GEN-LAST:event_btnRensaActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnMinSida;
    private javax.swing.JButton btnRensa;
    private javax.swing.JPasswordField jPasswordFieldNytt;
    private javax.swing.JPasswordField jPasswordFieldUpprepa;
    private javax.swing.JPasswordField jPasswordNuvarandeLosenord;
    private javax.swing.JLabel lblAndraLosenord;
    private javax.swing.JLabel lblNuvarandeLosenord;
    private javax.swing.JLabel lblNyttLosenord;
    private javax.swing.JLabel lblUpprepaLosenord;
    // End of variables declaration//GEN-END:variables
}
