package mib.p;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;

public class AndraLosenOrdAgentForm extends javax.swing.JPanel {
    String epost;
    String isAdmin;
    private static InfDB idb;
   
    /**
     * Creates new form AndraLosenOrdAgentForm
     */
    public AndraLosenOrdAgentForm(String epost, String isAdmin) {
        initComponents();
        
        this.epost= epost;
        this.isAdmin = isAdmin;
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMinSida = new javax.swing.JButton();
        lblAndraLosenord = new javax.swing.JLabel();
        btnAndra = new javax.swing.JButton();
        lblNuvarandeLosenord = new javax.swing.JLabel();
        lblNyttLosenord = new javax.swing.JLabel();
        lblUpprepaLosenord = new javax.swing.JLabel();
        jPasswordFieldUpprepa = new javax.swing.JPasswordField();
        jPasswordFieldNytt = new javax.swing.JPasswordField();
        jPasswordFieldNuvarandeLosenord = new javax.swing.JPasswordField();
        btnRensa = new javax.swing.JButton();

        btnMinSida.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        lblAndraLosenord.setFont(new java.awt.Font("MS Gothic", 1, 36)); // NOI18N
        lblAndraLosenord.setText("Ändra Lösenord");

        btnAndra.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnAndra.setText("Ändra");
        btnAndra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraActionPerformed(evt);
            }
        });

        lblNuvarandeLosenord.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblNuvarandeLosenord.setText("Nuvarande Lösenord:");

        lblNyttLosenord.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblNyttLosenord.setText("Ange Nytt Lösenord:");

        lblUpprepaLosenord.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblUpprepaLosenord.setText("Upprepa Lösenord:");

        btnRensa.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnRensa.setText("Rensa");
        btnRensa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRensaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(lblAndraLosenord))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblUpprepaLosenord)
                            .addComponent(lblNyttLosenord)
                            .addComponent(lblNuvarandeLosenord))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jPasswordFieldNuvarandeLosenord, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                                .addComponent(jPasswordFieldNytt))
                            .addComponent(jPasswordFieldUpprepa, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(136, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAndra)
                .addGap(18, 18, 18)
                .addComponent(btnRensa)
                .addGap(76, 76, 76)
                .addComponent(btnMinSida)
                .addGap(32, 32, 32))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAndraLosenord)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jPasswordFieldNuvarandeLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNuvarandeLosenord))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNyttLosenord)
                    .addComponent(jPasswordFieldNytt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUpprepaLosenord)
                    .addComponent(jPasswordFieldUpprepa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(btnMinSida)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAndra)
                            .addComponent(btnRensa))
                        .addGap(34, 34, 34))))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Denna knapp skickar en till MinSidaAgentForm.
    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(AndraLosenOrdAgentForm.this);
                frame.setContentPane(new MinSidaAgentForm(epost,isAdmin));
                frame.revalidate();
                frame.setTitle("Startsida: Agent");
                frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed

    private void btnAndraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraActionPerformed
        String losenord ="";
    try {
        String losenOrdCheck = idb.fetchSingle("SELECT Losenord FROM mibdb.agent WHERE epost = '" + epost + "'");
        losenord = losenOrdCheck;
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
        return; // Avsluta metoden om det uppstår ett fel vid hämtning av lösenordet
    }

    if (jPasswordFieldNytt.getText().equals(jPasswordFieldUpprepa.getText()) && jPasswordFieldNuvarandeLosenord.getText().equals(losenord)) {
        try {
            idb.update("UPDATE mibdb.agent SET Losenord='" + jPasswordFieldNytt.getText() + "' WHERE Epost='" + epost + "';");
            JOptionPane.showMessageDialog(null, "Lösenordet har ändrats.");
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel vid uppdatering av lösenordet.");
        }
    } else {
        JOptionPane.showMessageDialog(null, "Något gick fel. Försök igen.");
    }
    }//GEN-LAST:event_btnAndraActionPerformed
    // Denna knapp rensar det som står i lösenordfälten och fokuset sätts på nuvarande lösenord fältet.
    private void btnRensaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRensaActionPerformed
        jPasswordFieldNuvarandeLosenord.setText("");
        jPasswordFieldNytt.setText(""); 
        jPasswordFieldUpprepa.setText(""); 
        jPasswordFieldNuvarandeLosenord.requestFocus();
    }//GEN-LAST:event_btnRensaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndra;
    private javax.swing.JButton btnMinSida;
    private javax.swing.JButton btnRensa;
    private javax.swing.JPasswordField jPasswordFieldNuvarandeLosenord;
    private javax.swing.JPasswordField jPasswordFieldNytt;
    private javax.swing.JPasswordField jPasswordFieldUpprepa;
    private javax.swing.JLabel lblAndraLosenord;
    private javax.swing.JLabel lblNuvarandeLosenord;
    private javax.swing.JLabel lblNyttLosenord;
    private javax.swing.JLabel lblUpprepaLosenord;
    // End of variables declaration//GEN-END:variables
}
