/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/*
 * Detta är en JPanel-klass som visar användaren en formulärsida för att befordra en agent till administratör. 
 * Agenter som för närvarande inte har admin-status visas i en jComboBox.
 * När användaren trycker på knappen "Befordra" sätts den valda agenten till Administratör i databasen. 
 * Användaren kan också ta sig tillbaka till "Min sida" och "Admintjänster" med hjälp av knapparna på sidan.
 */
package mib.p;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author ASUS
 */
public class BefordraAgentForm extends javax.swing.JPanel {

    private String epost;
    private String isAdmin;
    private static InfDB idb;

    /**
     * Creates new form BefordraAgentForm
     */
    public BefordraAgentForm(String epost, String isAdmin) {
        initComponents();
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        this.epost = epost;
        this.isAdmin = isAdmin;
        setEjAdminComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboEjAdmin = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        btnMinSida = new javax.swing.JButton();
        btnAdminTjanster = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));
        setName(""); // NOI18N

        jComboEjAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agenter" }));

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Välj agent att göra till admin:");

        jButton1.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        jButton1.setText("Befordra");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnMinSida.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        btnAdminTjanster.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnAdminTjanster.setText("Admintjänster");
        btnAdminTjanster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminTjansterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jComboEjAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)))
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(btnAdminTjanster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinSida)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboEjAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 177, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinSida)
                    .addComponent(btnAdminTjanster))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String namn = null;
        if (!jComboEjAdmin.getSelectedItem().toString().equals("Agenter")) {
            namn = jComboEjAdmin.getSelectedItem().toString();
        }
        String query = "UPDATE mibdb.agent SET Administrator = 'J' WHERE Namn = '" + namn + "'";

        try {
            idb.update(query);
            resetEjAdminComboBox();
            setEjAdminComboBox();
            JOptionPane.showMessageDialog(null, namn + " har nu fått administratörstatus");
            
        } catch (InfException e) {

        }
    }//GEN-LAST:event_jButton1ActionPerformed
    public void resetEjAdminComboBox() {
      jComboEjAdmin.removeAllItems();
      jComboEjAdmin.addItem("Agenter");
      jComboEjAdmin.setSelectedIndex(0);
    }
    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(BefordraAgentForm.this);
        frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Startsida: Agent");
        frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed

    private void btnAdminTjansterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminTjansterActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(BefordraAgentForm.this);
        frame.setContentPane(new AdminFunktionerForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Administratörsfunktioner");
        frame.repaint();
    }//GEN-LAST:event_btnAdminTjansterActionPerformed

    private void setEjAdminComboBox() {
        String query = "SELECT namn FROM mibdb.agent WHERE Administrator = 'N'";
        ArrayList<String> ejAdminAgenter = null;

        try {
            ejAdminAgenter = idb.fetchColumn(query);
        } catch (InfException e) {

            System.out.println("Fel vid hämtning av ej-administratörer: " + e.getMessage());
        }
        for (String agent : ejAdminAgenter) {
            jComboEjAdmin.addItem(agent);
            
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminTjanster;
    private javax.swing.JButton btnMinSida;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboEjAdmin;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
