/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

 /**
 * Detta är en JPanel-klass som visar användaren en formulärsida för att befordra en agent till administratör,
 * Agenter som för närvarande inte har admin-status visas i en jComboBox,
 * När användaren trycker på knappen "Befordra" sätts den valda agenten till Administratör i databasen,
 * Användaren kan också ta sig tillbaka till "Min sida" och "Admintjänster" med hjälp av knapparna på sidan.
 */
package mib.p;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author ASUS
 */
public class BefordraAgentForm extends javax.swing.JPanel {

    private String epost;
    private String isAdmin;
    private static InfDB idb;

    /**
     * Creates new form BefordraAgentForm
     */
    public BefordraAgentForm(String epost, String isAdmin) {
        initComponents();
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        this.epost = epost;
        this.isAdmin = isAdmin;
        fyllEjAdminComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMinSida = new javax.swing.JButton();
        btnAdminTjanster = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnBefordra = new javax.swing.JButton();
        cbEjAdmin = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));
        setName(""); // NOI18N

        btnMinSida.setBackground(new java.awt.Color(242, 242, 242));
        btnMinSida.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        btnAdminTjanster.setBackground(new java.awt.Color(242, 242, 242));
        btnAdminTjanster.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnAdminTjanster.setText("Adminsida");
        btnAdminTjanster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminTjansterActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), null, null));

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Välj agent att göra till admin:");

        btnBefordra.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        btnBefordra.setText("Befordra");
        btnBefordra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBefordraActionPerformed(evt);
            }
        });

        cbEjAdmin.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Agenter" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cbEjAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBefordra))
                    .addComponent(jLabel1))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbEjAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBefordra))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnAdminTjanster)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinSida)
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinSida)
                    .addComponent(btnAdminTjanster))
                .addGap(17, 17, 17))
        );
    }// </editor-fold>//GEN-END:initComponents
/**
 * Metod kopplad till btnBefordra som med hjälp av InfDB-metoden update()
 * uppdaterar Administrator-kolumnen i agent-tabellen för vald agent, från "N" till "J", efter
 * att först ha validerat så ett val gjorts, genom metod från valideringsklassen,
 * seda körs metoderna resetEjAdminComboBox() och fyllEjAdminComboBox
 * för att återställa cbEjAdmin.
 * @param evt 
 */
    private void btnBefordraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBefordraActionPerformed
        String namn = null;
        if (ValideringsKlass.valideraComboBoxAktivtVal(cbEjAdmin)) {
            namn = cbEjAdmin.getSelectedItem().toString();
            
           
        }
        else{
        JOptionPane.showMessageDialog(null, "Var god välj att agent att befordra");
           }
        String query = "UPDATE mibdb.agent SET Administrator = 'J' WHERE Namn = '" + namn + "'";
        
        try {
            idb.update(query);
            resetEjAdminComboBox();
            fyllEjAdminComboBox();
            if(namn!=null)
            {
            JOptionPane.showMessageDialog(null, namn + " har nu fått administratörstatus");
            }

        } catch (InfException e) {

        }
    }//GEN-LAST:event_btnBefordraActionPerformed
    /**
     * Metod som återställer cbEjAdmin genom att ta bort allt innehåll och 
     * sedan lägga in "Agenter" på index 0.
     */
    public void resetEjAdminComboBox() {
        cbEjAdmin.removeAllItems();
        cbEjAdmin.addItem("Agenter");
        cbEjAdmin.setSelectedIndex(0);
    }
    /**
     * Metod kopplad till btnMinSida som fyller upp JFrame med en ny instans av
     * MinSidaAgentForm för att användaren ska kunna ta sig tillbaka till sin
     * sida, epost och isAdmin skickas med som parametrar för att initialiera en
     * ny "Min Sida", fönster-titeln sätts till "Startida: Agent" och fönstret
     * "målas om" för att visa "Min Sida"-panelen.
     *
     * @param evt
     */
    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(BefordraAgentForm.this);
        frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Startsida: Agent");
        frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed

    private void btnAdminTjansterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminTjansterActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(BefordraAgentForm.this);
        frame.setContentPane(new AdminFunktionerForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Administratörsfunktioner");
        frame.repaint();
    }//GEN-LAST:event_btnAdminTjansterActionPerformed
     /**
      * Fyller upp cbEjAdmin med namn på agenter som för tillfället inte har
      * admin-status, genom InfDB-metoden fetchColumn() som skapar en arraylist
      * med agent-namn som har "N" i Administrator-kolumnen, och denna arraylist
      * loopas sedan genom och agentnamnen läggs till im comboboxen.
      */
    private void fyllEjAdminComboBox() {
        String query = "SELECT namn FROM mibdb.agent WHERE Administrator = 'N'";
        ArrayList<String> ejAdminAgenter = null;

        try {
            ejAdminAgenter = idb.fetchColumn(query);
        } catch (InfException e) {

            System.out.println("Fel vid hämtning av ej-administratörer: " + e.getMessage());
        }
        for (String agent : ejAdminAgenter) {
            cbEjAdmin.addItem(agent);

        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminTjanster;
    private javax.swing.JButton btnBefordra;
    private javax.swing.JButton btnMinSida;
    private javax.swing.JComboBox<String> cbEjAdmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
