/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ASUS
 */
public class HanteraCheferForm extends javax.swing.JPanel {

    private static InfDB idb;
    private String epost;
    private String isAdmin;
    private ArrayList<String> omrade;
    private ArrayList<String> kontor;

    /**
     * Creates new form HanteraCheferForm
     */
    public HanteraCheferForm(String epost, String isAdmin) {
        initComponents();
        this.epost = epost;
        this.isAdmin = isAdmin;
        ArrayList<String> omrade = new ArrayList<>();
        ArrayList<String> kontor = new ArrayList<>();

        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        fyllArrayListor();
        fyllComboBoxar();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMinSida = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btnBytChef = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        lblOmrade = new javax.swing.JLabel();
        jComboOmradeChef = new javax.swing.JComboBox<>();
        btnHittaChef = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNuvarandeChef = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnBytChef1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        lblKontor = new javax.swing.JLabel();
        jComboKontor = new javax.swing.JComboBox<>();
        btnHittaChefKontor = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtNuvarandeChefKontor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAdminsida = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));

        btnMinSida.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));

        btnBytChef.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnBytChef.setText("Byt chef");

        lblOmrade.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblOmrade.setText("Område:");

        jComboOmradeChef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj område" }));

        btnHittaChef.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnHittaChef.setText("Hitta chef");
        btnHittaChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHittaChefActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Chef:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(lblOmrade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2)
                    .addComponent(jComboOmradeChef, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNuvarandeChef, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHittaChef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBytChef, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOmrade)
                    .addComponent(jComboOmradeChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHittaChef))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNuvarandeChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBytChef)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, null));

        btnBytChef1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnBytChef1.setText("Byt chef");

        lblKontor.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblKontor.setText("Kontor:");

        jComboKontor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj kontor" }));

        btnHittaChefKontor.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnHittaChefKontor.setText("Hitta chef");
        btnHittaChefKontor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHittaChefKontorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Chef:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lblKontor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField3)
                    .addComponent(jComboKontor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtNuvarandeChefKontor, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHittaChefKontor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBytChef1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblKontor)
                    .addComponent(jComboKontor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHittaChefKontor))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNuvarandeChefKontor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBytChef1)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Byt områdeschef:");

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Byt kontorschef:");

        btnAdminsida.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnAdminsida.setText("Adminsida");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAdminsida)
                            .addComponent(btnMinSida, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAdminsida)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnMinSida)
                        .addGap(9, 9, 9)))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHittaChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHittaChefActionPerformed
        txtNuvarandeChef.setText(getChefsNamn(jComboOmradeChef.getSelectedItem().toString()));
    }//GEN-LAST:event_btnHittaChefActionPerformed

    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(HanteraCheferForm.this);
        frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Startsida: Agent");
        frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed

    private void btnHittaChefKontorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHittaChefKontorActionPerformed
       txtNuvarandeChefKontor.setText(getChefsNamnKontor(jComboKontor.getSelectedItem().toString()));
    }//GEN-LAST:event_btnHittaChefKontorActionPerformed

    public int getAgentID(String omrade) {
        int agent = 0;
        String query = "SELECT Agent_ID "
                + "FROM mibdb.omradeschef "
                + "WHERE omrade IN "
                + "(SELECT Omrades_ID "
                + "FROM mibdb.omrade "
                + "WHERE Benamning = '" + omrade + "')";

        try {
            agent = Integer.parseInt(idb.fetchSingle(query));
        } catch (NumberFormatException e) {

            System.err.println("Fel vid konvertering av Agent_ID till heltal: " + e.getMessage());
        } catch (InfException e) {

            System.err.println("Fel vid databasåtkomst: " + e.getMessage());
        }

        return agent;
    }

    private String getChefsNamn(String omrade) {
        String chefsNamn;
        String query = "SELECT Namn "
                + "FROM mibdb.agent "
                + "WHERE mibdb.agent.Agent_ID IN ("
                + "    SELECT mibdb.omradeschef.Agent_ID "
                + "    FROM mibdb.omradeschef "
                + "    WHERE Omrade IN ("
                + "        SELECT Omrades_ID "
                + "        FROM mibdb.omrade "
                + "        WHERE Benamning = '" + omrade + "'"
                + "    )"
                + ")";
        try {
            chefsNamn = idb.fetchSingle(query);
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande: " + e.getMessage());
            return null; // Returnera null vid fel
        }
        return chefsNamn;
    }
  private String getChefsNamnKontor(String kontor) {
    String kontorsChef = null ;
    try {
        String query = "SELECT namn " +
                       "FROM mibdb.agent " +
                       "WHERE mibdb.agent.Agent_ID IN ( " +
                       "    SELECT mibdb.kontorschef.Agent_ID " +
                       "    FROM mibdb.kontorschef " +
                       "    WHERE Kontorsbeteckning = '" + kontor + "' " +
                       ")";
        kontorsChef = idb.fetchSingle(query);
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Något gick fel!");
        System.out.println("Internt felmeddelande: " + e.getMessage());
    }
    return kontorsChef;
}
    private void fyllArrayListor() {
        try {
            String query = "SELECT Benamning FROM mibdb.omrade";
            omrade = idb.fetchColumn(query);
            String query2 = "SELECT Kontorsbeteckning FROM mibdb.kontorschef";
            kontor = idb.fetchColumn(query2);
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande: " + ex.getMessage());
            omrade = new ArrayList<>();
        }

    }

    private void fyllComboBoxar() {
        for (String omradet : omrade) {
            jComboOmradeChef.addItem(omradet);
        }
        for (String kontoret : kontor)
        {
           jComboKontor.addItem(kontoret);
        }
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminsida;
    private javax.swing.JButton btnBytChef;
    private javax.swing.JButton btnBytChef1;
    private javax.swing.JButton btnHittaChef;
    private javax.swing.JButton btnHittaChefKontor;
    private javax.swing.JButton btnMinSida;
    private javax.swing.JComboBox<String> jComboKontor;
    private javax.swing.JComboBox<String> jComboOmradeChef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblKontor;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JTextField txtNuvarandeChef;
    private javax.swing.JTextField txtNuvarandeChefKontor;
    // End of variables declaration//GEN-END:variables
}
