/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ASUS
 */
public class HanteraCheferForm extends javax.swing.JPanel {

    private static InfDB idb;
    private String epost;
    private String isAdmin;
    private ArrayList<String> omrade;

    /**
     * Creates new form HanteraCheferForm
     */
    public HanteraCheferForm(String epost, String isAdmin) {
        initComponents();
        this.epost = epost;
        this.isAdmin = isAdmin;
        ArrayList<String> omrade = new ArrayList<>();

        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        fyllOmradesArrayList();
        fyllOmradesComboBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboOmradeChef = new javax.swing.JComboBox<>();
        btnHittaChef = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNuvarandeChef = new javax.swing.JTextField();
        btnBytChef = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Område:");

        jComboOmradeChef.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj område" }));

        btnHittaChef.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnHittaChef.setText("Hitta chef");
        btnHittaChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHittaChefActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Chef:");

        btnBytChef.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnBytChef.setText("Byt chef");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jComboOmradeChef, 0, 138, Short.MAX_VALUE)
                        .addComponent(txtNuvarandeChef)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnHittaChef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBytChef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(179, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboOmradeChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHittaChef))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNuvarandeChef, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBytChef)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(203, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnHittaChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHittaChefActionPerformed
        txtNuvarandeChef.setText(getChefsNamn(jComboOmradeChef.getSelectedItem().toString()));
    }//GEN-LAST:event_btnHittaChefActionPerformed

    public int getAgentID(String omrade) {
        int agent = 0;
        String query = "SELECT Agent_ID "
                + "FROM mibdb.omradeschef "
                + "WHERE omrade IN "
                + "(SELECT Omrades_ID "
                + "FROM mibdb.omrade "
                + "WHERE Benamning = '" + omrade + "')";

        try {
            agent = Integer.parseInt(idb.fetchSingle(query));
        } catch (NumberFormatException e) {

            System.err.println("Fel vid konvertering av Agent_ID till heltal: " + e.getMessage());
        } catch (InfException e) {

            System.err.println("Fel vid databasåtkomst: " + e.getMessage());
        }

        return agent;
    }

    private String getChefsNamn(String omrade) {
        String chefsNamn;
        String query = "SELECT Namn "
                + "FROM mibdb.agent "
                + "WHERE mibdb.agent.Agent_ID IN ("
                + "    SELECT mibdb.omradeschef.Agent_ID "
                + "    FROM mibdb.omradeschef "
                + "    WHERE Omrade IN ("
                + "        SELECT Omrades_ID "
                + "        FROM mibdb.omrade "
                + "        WHERE Benamning = '" + omrade + "'"
                + "    )"
                + ")";
        try {
            chefsNamn = idb.fetchSingle(query);
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande: " + ex.getMessage());
            return null; // Returnera null vid fel
        }
        return chefsNamn;
    }

    private void fyllOmradesArrayList() {
        try {
            String query = "SELECT Benamning FROM mibdb.omrade";
            omrade = idb.fetchColumn(query);
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande: " + ex.getMessage());
            omrade = new ArrayList<>();
        }

    }

    private void fyllOmradesComboBox() {
        for (String omrade : omrade) {
            jComboOmradeChef.addItem(omrade);
        }

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBytChef;
    private javax.swing.JButton btnHittaChef;
    private javax.swing.JComboBox<String> jComboOmradeChef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField txtNuvarandeChef;
    // End of variables declaration//GEN-END:variables
}
