/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import java.util.ArrayList;
import java.util.HashMap;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author samsung
 */
public class HittaAlienPlats extends javax.swing.JPanel {

    private static InfDB idb;
    /**
     * Creates new form HittaAlienPlats
     */
    public HittaAlienPlats() {
        initComponents();
        fyllComboBox();
        fyllScrollPane();
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }
    

    private void fyllScrollPane(){
        txtaListadeAliens.append("ID: \t");
        txtaListadeAliens.append("NAMN: \n");
    }
    
    private void fyllComboBox() {

        ArrayList<String> platser;
        try {
            platser = idb.fetchColumn("select benamning from plats");
            cbValjPlats.removeAllItems();
            for (String enPlats : platser) {
                cbValjPlats.addItem(enPlats);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        cbValjPlats = new javax.swing.JComboBox<>();
        btnVisaAliens = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaListadeAliens = new javax.swing.JTextArea();
        btnTillbaka = new javax.swing.JButton();

        lblRubrik.setText("Välj plats:");

        cbValjPlats.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnVisaAliens.setText("Visa aliens");
        btnVisaAliens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaAliensActionPerformed(evt);
            }
        });

        txtaListadeAliens.setColumns(20);
        txtaListadeAliens.setRows(5);
        jScrollPane2.setViewportView(txtaListadeAliens);

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbaka)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbValjPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(btnVisaAliens))
                    .addComponent(lblRubrik))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbValjPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisaAliens))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnTillbaka)
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
       JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(HittaAlienPlats.this);
                frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
                frame.revalidate();
                frame.setTitle("Startsida: Agent");
                frame.repaint();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnVisaAliensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaAliensActionPerformed
        String plats = cbValjPlats.getSelectedItem().toString();
        txtaListadeAliens.setText("");
        txtaListadeAliens.setEditable(false);
        fyllScrollPane();
        try {
            String fraga = "select alien.namn, alien_id from alien join plats on alien.plats = plats_id where plats.BENAMNING = '" + plats + "'";
            ArrayList<HashMap<String,String>>  alienLista = idb.fetchRows(fraga);
            for (HashMap<String,String> enMap : alienLista){
            String id = enMap.get("ALIEN_ID");
            String namn =enMap.get("NAMN");
            txtaListadeAliens.append(id + "\t");
            txtaListadeAliens.append(namn + "\n");
            
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        } catch (NullPointerException npe) {
            txtaListadeAliens.append("Det finns inga aliens på denna plats...");
        }
    }//GEN-LAST:event_btnVisaAliensActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JToggleButton btnVisaAliens;
    private javax.swing.JComboBox<String> cbValjPlats;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JTextArea txtaListadeAliens;
    // End of variables declaration//GEN-END:variables

    private void initComponents() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

}
