package mib.p;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;

/**InloggSidanForm är en JPanel-klass där användaren 
 * loggar in i systemet, epost och lösenord används
 * vid inloggningen, sidan tar in String AlienOrAgent
 * utifrån knapptryck på HuvudSidan, för att
 * hålla reda på om användaren är alien eller agent.
 *
 * @author ASUS
 * 
 */
public class InloggSidanForm extends javax.swing.JPanel {
    private static InfDB idb;

    String AlienOrAgent;

    /**
     * Creates new form InloggAlienForm
     */
    public InloggSidanForm(String AlienOrAgent) {
        initComponents();
        this.AlienOrAgent = AlienOrAgent;
        setAlienOrAgent();
        
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMiB = new javax.swing.JLabel();
        lblAlienOrAgent = new javax.swing.JLabel();
        btnLoggaIn = new javax.swing.JButton();
        lblEpost = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        txtAnvandarnamn = new javax.swing.JTextField();
        jPasswordFieldLoseonrd = new javax.swing.JPasswordField();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));

        lblMiB.setFont(new java.awt.Font("Segoe UI Black", 1, 48)); // NOI18N
        lblMiB.setText("MiB");

        lblAlienOrAgent.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblAlienOrAgent.setText("Alien");

        btnLoggaIn.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnLoggaIn.setText("Logga in");
        btnLoggaIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaInActionPerformed(evt);
            }
        });

        lblEpost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEpost.setText("Epost:");

        lblLosenord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLosenord.setText("Lösenord:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblEpost)
                            .addComponent(lblLosenord))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldLoseonrd, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(lblMiB))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(215, 215, 215)
                        .addComponent(btnLoggaIn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(243, 243, 243)
                        .addComponent(lblAlienOrAgent)))
                .addContainerGap(250, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblMiB)
                .addGap(21, 21, 21)
                .addComponent(lblAlienOrAgent)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEpost)
                    .addComponent(txtAnvandarnamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(jPasswordFieldLoseonrd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLoggaIn)
                .addContainerGap(113, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoggaInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaInActionPerformed
        
        // Texten som finns i fälten Epost och Lösenord tilldelas till dessa två variabler epostadress och losenord.
        String epostadress = txtAnvandarnamn.getText();
        String losenord = jPasswordFieldLoseonrd.getText();
       
       // Alien inloggning.
       if(AlienOrAgent.equals("Alien"))
       {
        try {
            
            // Variablerna tilldelas värde från mibdb-databasen.
            // Alien-AN varibler som representerar epostadressen för en alien från databasen samt lösenord.
            String ANepostadressDb = idb.fetchSingle("SELECT Epost FROM mibdb.alien WHERE Epost = '"+epostadress+"'");
            String ANlosenordDb = idb.fetchSingle("SELECT Losenord FROM mibdb.alien WHERE Epost = '"+epostadress+"'");
            
            
            // if-sats, om epostadressen samt lösenordet som skrivs i text fälteten är lika med infon från databasen, skickas användaren till MinSidaAlienForm.
            if(epostadress.equals(ANepostadressDb) && losenord.equals(ANlosenordDb)) {
               JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(InloggSidanForm.this);
                frame.setContentPane(new MinSidaAlienForm(txtAnvandarnamn.getText()));
                frame.revalidate();
                frame.setTitle("Startsida: Alien");
                frame.repaint();


            }
            
            // Om if-villkoret är "false" får användaren ett felmeddelande "Något gick fel!". 
            else {
                
                JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
            }
          
        }
        catch(InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
            
        }
       }
       // Agent inloggning.
       if(AlienOrAgent.equals("Agent"))
       {try {
            
            
            // Variablerna tilldelas värde från mibdb-databasen.
            // Agent-AT varibler som representerar epostadressen för en agent från databasen samt lösenordet.
            String isAdmin = idb.fetchSingle("select Administrator from mibdb.agent WHERE Epost = '" + epostadress + "';");
            String ATepostadressDb = idb.fetchSingle("SELECT Epost FROM mibdb.agent WHERE Epost = '"+epostadress+"'");
            String ATlosenordDb = idb.fetchSingle("SELECT Losenord FROM mibdb.agent WHERE Epost = '"+epostadress+"'");
            
            
            // if-sats, om epostadressen samt lösenordet som skrivs i text fälteten är lika med infon från databasen, skickas användaren till MinSidaAgentForm.
            if(epostadress.equals(ATepostadressDb) && losenord.equals(ATlosenordDb)) {
               JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(InloggSidanForm.this);
                frame.setContentPane(new MinSidaAgentForm(epostadress,isAdmin));
                frame.revalidate();
                frame.setTitle("Startsida: Agent"); 
                frame.repaint();


            }
            
            // Om if-villkoret är "false" får användaren ett felmeddelande "Något gick fel!". 
            else {
                
                JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
            }
          
        }
        catch(InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
            
        }
       }
           
    }//GEN-LAST:event_btnLoggaInActionPerformed

 
  
    private void setAlienOrAgent()
  {
   lblAlienOrAgent.setText(AlienOrAgent);
   
          
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLoggaIn;
    private javax.swing.JPasswordField jPasswordFieldLoseonrd;
    private javax.swing.JLabel lblAlienOrAgent;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblMiB;
    private javax.swing.JTextField txtAnvandarnamn;
    // End of variables declaration//GEN-END:variables
}
