/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * MinSidaAgentForm är en JPanel-klass som visar Agenternas hemsida i systemet,
 * den sida de kommer till vid inloggning, olika JButtons kan ta användaren till
 * andra delar av systemet.
 *
 * @author ASUS
 */
public class MinSidaAgentForm extends javax.swing.JPanel {

    private static InfDB idb;
    private final String epost;
    private final String isAdmin;
    public boolean tryckNrTva;
    /**
     * Creates new form MinSidaAgentForm
     *
     * @param epost
     * @param isAdmin
     */
    public MinSidaAgentForm(String epost, String isAdmin) {
        initComponents();

        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        this.epost = epost;
        this.isAdmin = isAdmin;
        tryckNrTva = false;

        btnAdminFunktioner.setVisible(false);
        btnAdminFunktioner.setEnabled(false);
        if (isAdmin.equals("J")) {
            btnAdminFunktioner.setVisible(true);
            btnAdminFunktioner.setEnabled(true);
        }
        setValkommen();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdminFunktioner = new javax.swing.JButton();
        btnRegisteraAlien = new javax.swing.JButton();
        btnSokFunktioner = new javax.swing.JButton();
        btnAndraLosenord = new javax.swing.JButton();
        btnAndraAlienInfo = new javax.swing.JButton();
        btnUtrustning = new javax.swing.JButton();
        btnHittaOmradesChef = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblAgentNamn = new javax.swing.JLabel();
        lblValkommen = new javax.swing.JLabel();
        btnToppLista = new javax.swing.JButton();
        btnLoggaUt = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));

        btnAdminFunktioner.setBackground(new java.awt.Color(242, 242, 242));
        btnAdminFunktioner.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnAdminFunktioner.setText("Admin-sida");
        btnAdminFunktioner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminFunktionerActionPerformed(evt);
            }
        });

        btnRegisteraAlien.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnRegisteraAlien.setText("Registrera alien");
        btnRegisteraAlien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisteraAlienActionPerformed(evt);
            }
        });

        btnSokFunktioner.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnSokFunktioner.setText("Sökfunktioner");
        btnSokFunktioner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSokFunktionerActionPerformed(evt);
            }
        });

        btnAndraLosenord.setBackground(new java.awt.Color(242, 242, 242));
        btnAndraLosenord.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnAndraLosenord.setText("Ändra Lösenord");
        btnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenordActionPerformed(evt);
            }
        });

        btnAndraAlienInfo.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnAndraAlienInfo.setText("Ändra alieninfo");
        btnAndraAlienInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraAlienInfoActionPerformed(evt);
            }
        });

        btnUtrustning.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnUtrustning.setText("Utrustning");
        btnUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtrustningActionPerformed(evt);
            }
        });

        btnHittaOmradesChef.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnHittaOmradesChef.setText("Hitta områdeschef");
        btnHittaOmradesChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHittaOmradesChefActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(204, 204, 204), new java.awt.Color(153, 153, 153), null, null));

        lblAgentNamn.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        lblAgentNamn.setText("Min sida");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(lblAgentNamn)
                .addContainerGap(78, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblAgentNamn)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        lblValkommen.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lblValkommen.setText("Välkommen:");

        btnToppLista.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnToppLista.setText("Topplista");
        btnToppLista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnToppListaActionPerformed(evt);
            }
        });

        btnLoggaUt.setBackground(new java.awt.Color(242, 242, 242));
        btnLoggaUt.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnLoggaUt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAndraLosenord)
                .addGap(98, 98, 98)
                .addComponent(btnAdminFunktioner)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnToppLista, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAndraAlienInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSokFunktioner, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRegisteraAlien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUtrustning, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHittaOmradesChef, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(lblValkommen))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(lblValkommen)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegisteraAlien)
                    .addComponent(btnSokFunktioner))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAndraAlienInfo)
                    .addComponent(btnUtrustning))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHittaOmradesChef)
                    .addComponent(btnToppLista))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdminFunktioner)
                    .addComponent(btnAndraLosenord)
                    .addComponent(btnLoggaUt))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents
 /**
  * Metod som genon InfDB-metoden fetchSingle hämtar namnet på den agent som precis loggat in
  * för att fylla lblAgentNamn med detta som välkomnsthälsning.
  */
    private void setValkommen() {
        try {
            lblAgentNamn.setText(idb.fetchSingle("SELECT Namn FROM mibdb.agent WHERE Epost = '" + epost + "'"));
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
        }
    }
    private void btnAdminFunktionerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminFunktionerActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAgentForm.this);
        frame.setContentPane(new AdminFunktionerForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Administratörsfunktioner");
        frame.repaint();
    }//GEN-LAST:event_btnAdminFunktionerActionPerformed

    private void btnRegisteraAlienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisteraAlienActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAgentForm.this);
        frame.setContentPane(new RegisteraAlienForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Registrera ny Alien");
        frame.repaint();
    }//GEN-LAST:event_btnRegisteraAlienActionPerformed

    private void btnSokFunktionerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSokFunktionerActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAgentForm.this);
        frame.setContentPane(new SokFunktionerForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Sök ras");
        frame.repaint();
    }//GEN-LAST:event_btnSokFunktionerActionPerformed

    private void btnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenordActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAgentForm.this);
        frame.setContentPane(new AndraLosenOrdAgentForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Ändra lösenord");
        frame.repaint();
    }//GEN-LAST:event_btnAndraLosenordActionPerformed

    private void btnAndraAlienInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraAlienInfoActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAgentForm.this);
        frame.setContentPane(new AndraAlienInfoForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Uppdatera Alien-information.");
        frame.repaint();
    }//GEN-LAST:event_btnAndraAlienInfoActionPerformed

    private void btnUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtrustningActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAgentForm.this);
        frame.setContentPane(new HanteraUtrustningForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Hantera utrustning");
        frame.repaint();
    }//GEN-LAST:event_btnUtrustningActionPerformed

    private void btnHittaOmradesChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHittaOmradesChefActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAgentForm.this);
        frame.setContentPane(new HittaOmradesChef(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Startsida: Agent");
        frame.repaint();
    }//GEN-LAST:event_btnHittaOmradesChefActionPerformed

    private void btnToppListaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnToppListaActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAgentForm.this);
        frame.setContentPane(new ToppTreKontaktAgentForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Topplista: Kontaktagenter");
        frame.repaint();
    }//GEN-LAST:event_btnToppListaActionPerformed
/**
 * Metod kopplad till btnLoggaUt, som vid första trycket ställer en kontrollfråga om man verkligen vill
 * logga ut, och vid andra trycket (vilket hålls reda på via boolean-variabel tryckNrTva) låter
 * användaren logga ut.
 * @param evt 
 */
    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
         if(tryckNrTva)
       {
           JOptionPane.showMessageDialog(null, "Hejdå, välkommen tillbaka!");
       JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAgentForm.this);
        frame.setContentPane(new InloggSidanForm("Agent"));
        frame.revalidate();
        frame.setTitle("Välkommen till MiB");
        frame.repaint();
       
       }
       else
       {
       JOptionPane.showMessageDialog(null, "Är du säker på att du vill logga ut? Klicka i såfall 'Logga ut' igen.");
       tryckNrTva = true;
       }
    }//GEN-LAST:event_btnLoggaUtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdminFunktioner;
    private javax.swing.JButton btnAndraAlienInfo;
    private javax.swing.JButton btnAndraLosenord;
    private javax.swing.JButton btnHittaOmradesChef;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnRegisteraAlien;
    private javax.swing.JButton btnSokFunktioner;
    private javax.swing.JButton btnToppLista;
    private javax.swing.JButton btnUtrustning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAgentNamn;
    private javax.swing.JLabel lblValkommen;
    // End of variables declaration//GEN-END:variables
}
