/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;

/**
 *
 * @author ASUS
 */
public class MinSidaAlienForm extends javax.swing.JPanel {
    String epost;
    String omradet;
    
    private static InfDB idb;
    

    /**
     * Creates new form MinSidaForm
     * @param epost
     */
    public MinSidaAlienForm(String epost) {
        initComponents();
        this.epost = epost;
       
        
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        setValkommen();
        setAnsvarigAgent();
        setOmrade();
        setOmradesChef();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMinSida = new javax.swing.JLabel();
        btnAndraLosenord = new javax.swing.JButton();
        lblValkommenNamn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblOmradesChef = new javax.swing.JLabel();
        btnChefKontakt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblOmrade = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAnsAgent = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));

        lblMinSida.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        lblMinSida.setText("Min sida");

        btnAndraLosenord.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        btnAndraLosenord.setText("Ändra lösenord");
        btnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenordActionPerformed(evt);
            }
        });

        lblValkommenNamn.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblValkommenNamn.setText("Välkommen Namn");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblOmradesChef.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblOmradesChef.setText("AAAAAAAAAAAAAAAAAAAAAAA");

        btnChefKontakt.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        btnChefKontakt.setText("Kontaktinfo");
        btnChefKontakt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChefKontaktActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOmradesChef, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChefKontakt)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOmradesChef)
                    .addComponent(btnChefKontakt))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblOmrade.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblOmrade.setText("AAAAAAAAAAAAAAAAAAAAAAA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lblOmrade)
                .addGap(20, 20, 20))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblAnsAgent.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblAnsAgent.setText("AAAAAAAAAAAAAAAAAAAAAAAA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAnsAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblAnsAgent)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAndraLosenord))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(lblMinSida))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(103, 103, 103)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblValkommenNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                        .addGap(0, 84, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblMinSida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblValkommenNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAndraLosenord)
                .addGap(6, 6, 6))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenordActionPerformed
     JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAlienForm.this);
                frame.setContentPane(new AndraLosenOrdAlienForm(epost));
                frame.revalidate();
                frame.setTitle("Ändra lösenord");
                frame.repaint();
                
    }//GEN-LAST:event_btnAndraLosenordActionPerformed

    private void btnChefKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChefKontaktActionPerformed
      
        try {
    HashMap<String, String> agent = idb.fetchRow("SELECT * FROM MIBDB.AGENT WHERE MIBDB.AGENT.AGENT_ID IN (SELECT MIBDB.OMRADESCHEF.AGENT_ID FROM MIBDB.OMRADESCHEF WHERE OMRADE IN (SELECT OMRADES_ID FROM MIBDB.OMRADE WHERE BENAMNING = '" + omradet + "'))");
    JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAlienForm.this);
                frame.setContentPane(new OmradesChefForm(agent,omradet,epost));
                frame.revalidate();
                frame.setTitle("Områdeschef: Information");
                frame.repaint();

    
} catch (InfException e) {
    // Hantera eventuellt undantag här
    JOptionPane.showMessageDialog(null, "Ett fel uppstod: " + e.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);
    
}
    }//GEN-LAST:event_btnChefKontaktActionPerformed
   private void setValkommen()
   {
       try {
   
   lblValkommenNamn.setText("Välkommen "+idb.fetchSingle("SELECT Namn FROM mibdb.alien WHERE Epost = '"+epost+"'"));
   }
       catch(InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
       }}
   private void setAnsvarigAgent()
   {
        try {
            String ansAgent = idb.fetchSingle("SELECT namn FROM mibdb.agent WHERE Agent_ID IN (SELECT Ansvarig_Agent FROM mibdb.alien WHERE Epost = \"" + epost + "\")");
       lblAnsAgent.setText("Ansvarig agent:  "+ansAgent);
       lblAnsAgent.setVisible(true);
      }
        catch(InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
       }}
  private void setOmrade() {
    try {
        String omrade = idb.fetchSingle("SELECT Benamning FROM mibdb.omrade WHERE Omrades_ID IN (SELECT Finns_I FROM mibdb.plats WHERE Plats_ID IN (SELECT Plats FROM mibdb.alien WHERE Epost = '" + epost + "'))");
        lblOmrade.setText("Område:          " + omrade);
        lblOmrade.setVisible(true);
        omradet = omrade;
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
    }
} 
 
  private void setOmradesChef() {
    try {
         
        String omradesChef = idb.fetchSingle("SELECT Namn FROM mibdb.agent WHERE mibdb.agent.Agent_ID IN (SELECT mibdb.omradeschef.Agent_ID FROM mibdb.omradeschef WHERE Omrade IN (SELECT Omrades_ID FROM mibdb.omrade WHERE Benamning = '" + omradet + "'));");
        lblOmradesChef.setText("Områdeschef:     " + omradesChef);
        lblOmradesChef.setVisible(true);
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
    }
}
           
   
   
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraLosenord;
    private javax.swing.JButton btnChefKontakt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAnsAgent;
    private javax.swing.JLabel lblMinSida;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblOmradesChef;
    private javax.swing.JLabel lblValkommenNamn;
    // End of variables declaration//GEN-END:variables
}
