/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.HashMap;

/**
 * MinSidaAlienForm är en JPanel-klass som visar hemsidan för en alien när denne
 * loggar in i systemet, den får info om kontakt-agent, aktuellt område denne
 * alien tillhör, och namn på områdeschefen, Alien kan välja att se mer
 * information om chefen, eller ändra sitt lösenord.
 *
 * @author ASUS
 */
public class MinSidaAlienForm extends javax.swing.JPanel {

    String epost;
    String omradet;

    private static InfDB idb;

    /**
     * Creates new form MinSidaForm
     *
     * @param epost
     */
    public MinSidaAlienForm(String epost) {
        initComponents();
        this.epost = epost;

        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        setValkommen();
        setAnsvarigAgent();
        setOmrade();
        setOmradesChef();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMinSida = new javax.swing.JLabel();
        btnAndraLosenord = new javax.swing.JButton();
        lblValkommenNamn = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblOmradesChef = new javax.swing.JLabel();
        btnChefKontakt = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblOmrade = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblAnsAgent = new javax.swing.JLabel();
        btnLoggaUt = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));

        lblMinSida.setFont(new java.awt.Font("MS Gothic", 1, 48)); // NOI18N
        lblMinSida.setText("Min sida");

        btnAndraLosenord.setBackground(new java.awt.Color(242, 242, 242));
        btnAndraLosenord.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        btnAndraLosenord.setText("Ändra lösenord");
        btnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenordActionPerformed(evt);
            }
        });

        lblValkommenNamn.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblValkommenNamn.setText("Välkommen Namn");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblOmradesChef.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblOmradesChef.setText("AAAAAAAAAAAAAAAAAAAAAAA");

        btnChefKontakt.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        btnChefKontakt.setText("Kontaktinfo");
        btnChefKontakt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChefKontaktActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblOmradesChef, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnChefKontakt)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOmradesChef)
                    .addComponent(btnChefKontakt))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblOmrade.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblOmrade.setText("AAAAAAAAAAAAAAAAAAAAAAA");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(lblOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(lblOmrade)
                .addGap(20, 20, 20))
        );

        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lblAnsAgent.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblAnsAgent.setText("AAAAAAAAAAAAAAAAAAAAAAAA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblAnsAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(lblAnsAgent)
                .addGap(20, 20, 20))
        );

        btnLoggaUt.setBackground(new java.awt.Color(242, 242, 242));
        btnLoggaUt.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        btnLoggaUt.setText("Logga ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 93, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(btnLoggaUt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAndraLosenord)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(158, 158, 158)
                .addComponent(lblMinSida)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValkommenNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblMinSida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblValkommenNamn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLoggaUt)
                    .addComponent(btnAndraLosenord))
                .addGap(5, 5, 5))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenordActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAlienForm.this);
        frame.setContentPane(new AndraLosenOrdAlienForm(epost));
        frame.revalidate();
        frame.setTitle("Ändra lösenord");
        frame.repaint();

    }//GEN-LAST:event_btnAndraLosenordActionPerformed
    /**
     * Metod kopplad till btnChefKontakt,som utifrån texten för chefsnamn hämtar
     * all info om vald chef, genom InfDB-metoden fetchRow och lagrar det i en
     * HashMap, som sedan skickas med som parameter när en ny instans av
     * OmradesChefForm initieras.
     *
     * @param evt
     */
    private void btnChefKontaktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChefKontaktActionPerformed

        try {
            HashMap<String, String> agent = idb.fetchRow("SELECT * FROM MIBDB.AGENT WHERE MIBDB.AGENT.AGENT_ID IN (SELECT MIBDB.OMRADESCHEF.AGENT_ID FROM MIBDB.OMRADESCHEF WHERE OMRADE IN (SELECT OMRADES_ID FROM MIBDB.OMRADE WHERE BENAMNING = '" + omradet + "'))");
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAlienForm.this);
            frame.setContentPane(new OmradesChefForm(agent, omradet, epost));
            frame.revalidate();
            frame.setTitle("Områdeschef: Information");
            frame.repaint();

        } catch (InfException e) {

            JOptionPane.showMessageDialog(null, "Ett fel uppstod: " + e.getMessage(), "Fel", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnChefKontaktActionPerformed
    /**
     * Metod kopplad till btnLoggaUt, som visar en JOptionPane med alternativen
     * "Avbryt" eller "Logga ut", väljer man avbryt händer inget annat än att JOptionPane
     * stängs ner, väljer man "Logga ut så fortsätter utloggningen. 
     * Utförligare kommentarer finns i koden.
     *
     * @param evt
     */
    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        String[] alternativ = {"Logga ut", "Avbryt"};//En string-array("alternativ") skapas med strängarna "Logga ut och "Avbryt".

        int val = JOptionPane.showOptionDialog(null, "Är du säker på att du vill logga ut?",
                "Bekräfta utloggning", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE,
                null, alternativ, alternativ[1]);//Strängarna från "alternativ" sätts som text till JOptionPane-knapparna, index 1("Avbryt") blir standardvalet.
        // int val får värde genom knapptryckning på JOptionPane utifrån valets plats i alternativ-arrayen.
        // 1 = "Avrbryt" och 0 = "Logga ut".
        if (val == 0) { //int val kollas med if-satsen och är värdet 0 ("Logga ut") så fortsätter utloggning
            // och man tas till inloggningssidan, är värdet 1 så händer ingenting.
            JOptionPane.showMessageDialog(null, "Hejdå, välkommen tillbaka!");
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(MinSidaAlienForm.this);
            frame.setContentPane(new InloggSidanForm("Alien"));
            frame.revalidate();
            frame.setTitle("Välkommen till MiB");
            frame.repaint();
        }
    }//GEN-LAST:event_btnLoggaUtActionPerformed
    /**
     * Metod som genom InfDB-metoden fetchSingle hämtar namnet på inloggad alien
     * och sedan sätter lblValkommenNamn med namnet som en välkomsthälsning.
     */
    private void setValkommen() {
        try {

            lblValkommenNamn.setText("Välkommen " + idb.fetchSingle("SELECT Namn FROM mibdb.alien WHERE Epost = '" + epost + "'"));
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
        }
    }

    /**
     * Metod som genom InfDB-metoden fetchSingle hämtar namnet på den agent som
     * är kontaktagent åt inloggad alien, och sedan sätter lblAnsAgent med
     * namnet.
     */
    private void setAnsvarigAgent() {
        try {
            String ansAgent = idb.fetchSingle("SELECT namn FROM mibdb.agent WHERE Agent_ID IN (SELECT Ansvarig_Agent FROM mibdb.alien WHERE Epost = \"" + epost + "\")");
            lblAnsAgent.setText("Ansvarig agent:  " + ansAgent);
            lblAnsAgent.setVisible(true);
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
        }
    }

    /**
     * Metod som genom InfDB-metoden fetchSingle hämtar namnet på det område där
     * inloggad alien vistas, och sedan sätter lblOmrade med namnet.
     */
    private void setOmrade() {
        try {
            String omrade = idb.fetchSingle("SELECT Benamning FROM mibdb.omrade WHERE Omrades_ID IN (SELECT Finns_I FROM mibdb.plats WHERE Plats_ID IN (SELECT Plats FROM mibdb.alien WHERE Epost = '" + epost + "'))");
            lblOmrade.setText("Område:          " + omrade);
            lblOmrade.setVisible(true);
            omradet = omrade;
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
        }
    }

    /**
     * Metod som genom InfDB-metoden fetchSingle hämtar namnet på den chef som
     * är områdeschef över det område där inloggad alien vistas, och sedan
     * sätter lblOmradesChef med namnet.
     */
    private void setOmradesChef() {
        try {

            String omradesChef = idb.fetchSingle("SELECT Namn FROM mibdb.agent WHERE mibdb.agent.Agent_ID IN (SELECT mibdb.omradeschef.Agent_ID FROM mibdb.omradeschef WHERE Omrade IN (SELECT Omrades_ID FROM mibdb.omrade WHERE Benamning = '" + omradet + "'));");
            lblOmradesChef.setText("Områdeschef:     " + omradesChef);
            lblOmradesChef.setVisible(true);
        } catch (InfException e) {
            JOptionPane.showMessageDialog(null, "Något gick fel, testa igen!");
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraLosenord;
    private javax.swing.JButton btnChefKontakt;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblAnsAgent;
    private javax.swing.JLabel lblMinSida;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblOmradesChef;
    private javax.swing.JLabel lblValkommenNamn;
    // End of variables declaration//GEN-END:variables
}
