/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;


import java.util.logging.Level;
import java.util.logging.Logger;


/**
 *
 * @author samsung
 */
public class RegistreraUtrustning2 extends javax.swing.JPanel {
    private String epost;
    private String isAdmin;
    private static InfDB idb;

    /**
     * Creates new form RegistreraUtrustning2
     */
    public RegistreraUtrustning2(String epost, String isAdmin) {
        initComponents();
        this.epost = epost;
        this.isAdmin = isAdmin;
        fyllTypLista();
        
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        lblValjTyp = new javax.swing.JLabel();
        cbUtrustningsTyp = new javax.swing.JComboBox<>();
        lblValjTyp1 = new javax.swing.JLabel();
        tfAngivetNamn = new javax.swing.JTextField();
        btnLaggTill = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();

        lblRubrik.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        lblRubrik.setText("Registrera utrustning");

        lblValjTyp.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblValjTyp.setText("Välj typ:");

        cbUtrustningsTyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblValjTyp1.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblValjTyp1.setText("Namnge:");

        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnTillbaka)
                            .addComponent(btnLaggTill)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblValjTyp))
                            .addComponent(cbUtrustningsTyp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAngivetNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lblValjTyp1))
                            .addComponent(lblRubrik))))
                .addContainerGap(126, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblRubrik)
                .addGap(26, 26, 26)
                .addComponent(lblValjTyp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbUtrustningsTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblValjTyp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAngivetNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnLaggTill)
                .addGap(18, 18, 18)
                .addComponent(btnTillbaka)
                .addContainerGap(41, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(RegistreraUtrustning2.this);
                frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
                frame.revalidate();
                frame.setTitle("Startsida: Agent");
                frame.repaint();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        
        String utrustningsTyp = cbUtrustningsTyp.getSelectedItem().toString();
        String benamning = tfAngivetNamn.getText();
        if (ValideringsKlass.giltigtNamn(benamning)) {
            try {
                ArrayList<String> existerandeUtrustningsBenamningar = idb.fetchColumn("select benamning from utrustning");
                if (!ValideringsKlass.vardeFinns(benamning, existerandeUtrustningsBenamningar)) {
                    String id = idb.getAutoIncrement("utrustning", "utrustnings_id");
                    idb.insert("insert into utrustning values (" + id + ", " + "'" + benamning + "')");
                    kollaTyp(utrustningsTyp, id);
                } else {
                    JOptionPane.showMessageDialog(null, "Det finns redan utrustning registrerad med angiven benamning!");
                }
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Något gick fel!");
            }
        }
    }//GEN-LAST:event_btnLaggTillActionPerformed

    private void fyllTypLista() {
        cbUtrustningsTyp.removeAllItems();
        cbUtrustningsTyp.addItem("Vapen");
        cbUtrustningsTyp.addItem("Kommunikation");
        cbUtrustningsTyp.addItem("Teknik");
    }
    
    private void kollaTyp(String utrustningsTyp, String id) {
        if (utrustningsTyp.equals("Vapen")) {
            new RegistreraVapen(id, epost, isAdmin).setVisible(true);
        } else if (utrustningsTyp.equals("Kommunikation")) {
            new RegistreraKommunikation(id, epost, isAdmin).setVisible(true);
        } else if (utrustningsTyp.equals("Teknik")) {
            new RegistreraTeknik(id, epost, isAdmin).setVisible(true);
        }
        //dispose(); funkar inte ?? kanske inte behövs
        // - kolla vad som händer när sidan tar dig vidare till nästa steg, stängs detta?
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbUtrustningsTyp;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblValjTyp;
    private javax.swing.JLabel lblValjTyp1;
    private javax.swing.JTextField tfAngivetNamn;
    // End of variables declaration//GEN-END:variables
}
