/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;


import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;


/**
 * Registrera utrustning låter agenten skapa nya instanser av utrustning. 
 * De behöver välja utrustningstyp, vilket leder till separata fönster där data 
 * lagras i respektive tabell eftersom det inte bara är en utrustningstabell.
 * @author samsung
 */
public class RegistreraUtrustning extends javax.swing.JPanel {
    private String epost;
    private String isAdmin;
    private static InfDB idb;

    /**
     * Creates new form RegistreraUtrustning
     */
    public RegistreraUtrustning(String epost, String isAdmin) {
        initComponents();
        this.epost = epost;
        this.isAdmin = isAdmin;
        fyllTypLista();
        
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        btnMinSida = new javax.swing.JButton();
        btnHanteraUtrustning = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblUtrustningstyp = new javax.swing.JLabel();
        cbUtrustningsTyp = new javax.swing.JComboBox<>();
        lblValjTyp1 = new javax.swing.JLabel();
        tfAngivetNamn = new javax.swing.JTextField();
        btnLaggTill = new javax.swing.JButton();

        lblRubrik.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lblRubrik.setText("Registrera utrustning");

        btnMinSida.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        btnHanteraUtrustning.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnHanteraUtrustning.setText("Utrustning");
        btnHanteraUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHanteraUtrustningActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 153, 153), new java.awt.Color(204, 204, 204), null, null));

        lblUtrustningstyp.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblUtrustningstyp.setText("Utrustningstyp:");

        cbUtrustningsTyp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj typ" }));

        lblValjTyp1.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblValjTyp1.setText("Namnge:");

        btnLaggTill.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(btnLaggTill))
                            .addComponent(cbUtrustningsTyp, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfAngivetNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(lblValjTyp1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(lblUtrustningstyp)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblUtrustningstyp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbUtrustningsTyp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblValjTyp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfAngivetNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnLaggTill)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(126, Short.MAX_VALUE)
                        .addComponent(lblRubrik)
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(btnHanteraUtrustning)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnMinSida)
                .addGap(43, 43, 43))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(lblRubrik)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinSida)
                    .addComponent(btnHanteraUtrustning))
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(RegistreraUtrustning.this);
                frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
                frame.revalidate();
                frame.setTitle("Startsida: Agent");
                frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        JComboBox box = cbUtrustningsTyp;
        String utrustningsTyp = cbUtrustningsTyp.getSelectedItem().toString();
        String benamning = tfAngivetNamn.getText();
        if (ValideringsKlass.giltigtNamn(benamning) && ValideringsKlass.valideraComboBoxAktivtVal(box)) {
            try {
                ArrayList<String> existerandeUtrustningsBenamningar = idb.fetchColumn("select benamning from utrustning");
                if (!ValideringsKlass.vardeFinns(benamning, existerandeUtrustningsBenamningar)) {
                    String id = idb.getAutoIncrement("utrustning", "utrustnings_id");
                    idb.insert("insert into utrustning values (" + id + ", " + "'" + benamning + "')");
                    kollaTyp(utrustningsTyp, id);
                } else {
                    JOptionPane.showMessageDialog(null, "Det finns redan utrustning registrerad med angiven benamning!");
                }
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Något gick fel!");
            }
        }
    }//GEN-LAST:event_btnLaggTillActionPerformed

    private void btnHanteraUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHanteraUtrustningActionPerformed
       JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(RegistreraUtrustning.this);
                frame.setContentPane(new HanteraUtrustningForm(epost, isAdmin));
                frame.revalidate();
                frame.setTitle("Hantera utrustning");
                frame.repaint();
    }//GEN-LAST:event_btnHanteraUtrustningActionPerformed
    
    //Denna metod gör det möjligt att välja typ i en "drop down meny" istället
    //för att användaren ska behöva skriva in det manuellt
    private void fyllTypLista() {
        cbUtrustningsTyp.removeAllItems();
        cbUtrustningsTyp.addItem("Vapen");
        cbUtrustningsTyp.addItem("Kommunikation");
        cbUtrustningsTyp.addItem("Teknik");
    }
    
    //Denna metod används i LaggTillknappens actionperformed. 
    //Kontrollerar vilken sorts utrustningstyp man vill registrera och
    //öppnar sedan rätt fortsättningsfönster för vidare datainput.
    private void kollaTyp(String utrustningsTyp, String id) {
        if (utrustningsTyp.equals("Vapen")) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(RegistreraUtrustning.this);
                frame.setContentPane(new RegistreraVapen(id, epost, isAdmin));
                frame.revalidate();
                frame.setTitle("Registrera vapen");
                frame.repaint();
        } else if (utrustningsTyp.equals("Kommunikation")) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(RegistreraUtrustning.this);
                frame.setContentPane(new RegistreraKommunikation(id, epost, isAdmin));
                frame.revalidate();
                frame.setTitle("Registrera kommunikation");
                frame.repaint();
        } else if (utrustningsTyp.equals("Teknik")) {
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(RegistreraUtrustning.this);
                frame.setContentPane(new RegistreraTeknik(id, epost, isAdmin));
                frame.revalidate();
                frame.setTitle("Registrera teknik");
                frame.repaint();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHanteraUtrustning;
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JButton btnMinSida;
    private javax.swing.JComboBox<String> cbUtrustningsTyp;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JLabel lblUtrustningstyp;
    private javax.swing.JLabel lblValjTyp1;
    private javax.swing.JTextField tfAngivetNamn;
    // End of variables declaration//GEN-END:variables
}
