/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author ASUS
 */
public class RegisteraForm extends javax.swing.JPanel {
     private static InfDB idb;
    private int alienID;
    private String epost;
    String isAdmin;
    ValideringsKlass validering = new ValideringsKlass();
    
    /**
     * Creates new form RegisteraForm
     * @param epost
     * @param isAdmin
     */
    public RegisteraForm(String epost,String isAdmin) {
       initComponents();
         try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
      setAlienID();
      txtNamnReg.requestFocus();
      this.epost = epost;
      this.isAdmin = isAdmin;
    
      
                 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamn = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblEpost = new javax.swing.JLabel();
        lblRegDatum = new javax.swing.JLabel();
        lblPlats = new javax.swing.JLabel();
        lblAnsvarigAgent = new javax.swing.JLabel();
        txtTelReg = new javax.swing.JTextField();
        txtEpostReg = new javax.swing.JTextField();
        txtDatumReg = new javax.swing.JTextField();
        txtPlatsReg = new javax.swing.JTextField();
        txtAnsvAgent = new javax.swing.JTextField();
        btnRegistrera = new javax.swing.JButton();
        txtLosenOrdReg = new javax.swing.JTextField();
        lblLosenord = new javax.swing.JLabel();
        txtNamnReg = new javax.swing.JTextField();
        btnMinSida = new javax.swing.JButton();
        lblRas = new javax.swing.JLabel();
        jComboBoxValjRas = new javax.swing.JComboBox<>();
        txtVarierande = new javax.swing.JTextField();
        lblVarierande = new javax.swing.JLabel();
        lblRegistreraAlien = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));
        setPreferredSize(new java.awt.Dimension(550, 343));

        lblNamn.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNamn.setText("Namn:");

        lblTelefon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefon.setText("Telefon:");

        lblEpost.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblEpost.setText("Epost:");

        lblRegDatum.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRegDatum.setText("Reg-datum(YYYY-MM-DD):");

        lblPlats.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPlats.setText("Plats:");

        lblAnsvarigAgent.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAnsvarigAgent.setText("Ansvarig Agent:");

        btnRegistrera.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnRegistrera.setText("Registrera");
        btnRegistrera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistreraActionPerformed(evt);
            }
        });

        lblLosenord.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLosenord.setText("Lösenord:");

        btnMinSida.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        lblRas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRas.setText("Ras:");

        jComboBoxValjRas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj ras", "Boglodite\t", "Squid", "Worm" }));
        jComboBoxValjRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxValjRasActionPerformed(evt);
            }
        });

        lblVarierande.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblVarierande.setText("...........");

        lblRegistreraAlien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRegistreraAlien.setText("Registrera Alien");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblPlats)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtPlatsReg, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblAnsvarigAgent)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtAnsvAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblRegDatum)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtDatumReg, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(lblLosenord)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtLosenOrdReg, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblEpost)
                                .addComponent(lblTelefon))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTelReg, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtEpostReg, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblRas)
                            .addComponent(lblNamn))
                        .addGap(124, 124, 124)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNamnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxValjRas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblVarierande)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtVarierande, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnRegistrera)
                .addGap(113, 113, 113)
                .addComponent(btnMinSida)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(lblRegistreraAlien)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRegistreraAlien)
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRas)
                    .addComponent(jComboBoxValjRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNamnReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVarierande)
                    .addComponent(txtVarierande, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEpostReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEpost))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlatsReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlats))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAnsvAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnsvarigAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenord)
                    .addComponent(txtLosenOrdReg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRegistrera)
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinSida)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistreraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistreraActionPerformed
    String namn = txtNamnReg.getText();
    String eposten = txtEpostReg.getText();
    String telnr = txtTelReg.getText();
    String datum = txtDatumReg.getText();
    String losenord = txtLosenOrdReg.getText();
    int ansvAgent;
    int plats;
    
    if (!ValideringsKlass.validateTextFieldNotEmpty(namn)) {
    JOptionPane.showMessageDialog(null, "Namnetfältet får inte vara tomt.");
    return;
}

if (!ValideringsKlass.validateTextFieldNotEmpty(epost)) {
    JOptionPane.showMessageDialog(null, "E-postfältet får inte vara tom.");
    return;
}

if (!ValideringsKlass.validateTextFieldNotEmpty(telnr)) {
    JOptionPane.showMessageDialog(null, "Telefonnummerfältet får inte vara tomt.");
    return;
}

if (!ValideringsKlass.validateTextFieldNotEmpty(datum)) {
    JOptionPane.showMessageDialog(null, "Datumefältet får inte vara tomt.");
    return;
}

if (!ValideringsKlass.validateTextFieldNotEmpty(losenord)) {
    JOptionPane.showMessageDialog(null, "Lösenordsfältet får inte vara tomt.");
    return;
}

    if (!ValideringsKlass.valideraInt(txtVarierande.getText())) {
        JOptionPane.showMessageDialog(null, "Ange heltalssiffror för" + lblVarierande.getText());
        return;
    }
    
    if(!ValideringsKlass.valideraDatum(datum))
    {
     JOptionPane.showMessageDialog(null, "Ange datum enligt format: YYYY-MM-DD.");
        return;
    }

    // Validerar så att Ansvarig Agent anges med heltalsvärde.
    if (!ValideringsKlass.valideraInt(txtAnsvAgent.getText())) {
        JOptionPane.showMessageDialog(null, "Ange heltalssiffra för Ansvarig Agent.");
        return;
    }
    ansvAgent = Integer.parseInt(txtAnsvAgent.getText());

    // Validerar så att plats anges med heltalsvärde.
    if (!ValideringsKlass.valideraInt(txtPlatsReg.getText())) {
        JOptionPane.showMessageDialog(null, "Ange heltalssiffra för Plats.");
        return;
    }
    plats = Integer.parseInt(txtPlatsReg.getText());

    // Kontrollerar om e-postadressen redan finns registrerad, då E-post används för att unikt identifiera varje Alien.
    if (ValideringsKlass.checkEpost(eposten)) {
        JOptionPane.showMessageDialog(null, "E-postadressen finns redan i databasen.");
        return;
    }

    try {
        idb.insert("INSERT INTO mibdb.alien VALUES (" + alienID + ", '" + datum + "', '" + eposten + "', '" + losenord + "', '" + namn + "', '" + telnr + "', " + plats + ", " + ansvAgent + ")");
        JOptionPane.showMessageDialog(null, "Alien " + namn + " har registrerats i databasen.");
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Ett fel uppstod vid infogning av data.");
        return;
    }

    String valdRas = jComboBoxValjRas.getSelectedItem().toString();

    if (valdRas.equals("Squid")) {
        setRas("Squid", alienID, "Antal_Armar");
    } else if (valdRas.equals("Worm")) {
        setRas("Worm", alienID, "Langd");
    } else if (valdRas.equals("Boglodite")) {
        setRas("Boglodite", alienID, "Antal_Boogies");
    }

    clearTextFalt();
    setAlienID();
    }//GEN-LAST:event_btnRegistreraActionPerformed

    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
       JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(RegisteraForm.this);
                frame.setContentPane(new MinSidaAgentForm(epost,isAdmin));
                frame.revalidate();
                frame.setTitle("Startsida: Agent");
                frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed

    /**
     * Återställer textfälten och comboBoxen.
     */
    private void clearTextFalt()
    {
     lblVarierande.setText("....");
     txtVarierande.setText("");
     txtNamnReg.setText("");
     txtPlatsReg.setText("");
     txtTelReg.setText("");
     txtLosenOrdReg.setText("");
     txtEpostReg.setText("");
     txtDatumReg.setText("");
     txtAnsvAgent.setText("");
     jComboBoxValjRas.setSelectedIndex(0);
     
    }
    
     private boolean setRas(String ras, int alienID, String varierandeColumn) {
    if (!ValideringsKlass.valideraInt(txtVarierande.getText())) {
        JOptionPane.showMessageDialog(null, "Ange " + varierandeColumn + " med en giltig datatyp.");
        return false;
    }

    try {
        int varierande = Integer.parseInt(txtVarierande.getText());
        String insertQuery = "INSERT INTO mibdb." + ras.toLowerCase() + " (Alien_ID, " + varierandeColumn + ") VALUES (" + alienID + ", " + varierande + ")";
        System.out.println(ras + " insert query: " + insertQuery);
        idb.insert(insertQuery);
        return true;
        
    } catch (InfException e) {
        JOptionPane.showMessageDialog(null, "Ett fel uppstod vid infogning av " + ras + "-raden: " + e.getMessage());
        return false;
    }
}
    
    private void jComboBoxValjRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxValjRasActionPerformed
        String ras = ((String) jComboBoxValjRas.getSelectedItem()).trim();
    
    if (ras.equals("Squid")) {
        lblVarierande.setText("Antal armar:");
    } else if (ras.equals("Worm")) {
        lblVarierande.setText("Längd:");
    } else if (ras.equals("Boglodite")) {
        lblVarierande.setText("Antal boogies:");
    }
    }//GEN-LAST:event_jComboBoxValjRasActionPerformed
private void setAlienID()
{
        try {
    String alienIDStr = idb.getAutoIncrement("alien", "Alien_ID");
    alienID = Integer.parseInt(alienIDStr);
    
    

  
} catch (InfException e) {
    // Hantera undantag vid frågefel
    JOptionPane.showMessageDialog(null, "Ett fel uppstod vid generering av Alien-ID. Vänligen försök igen.");
}
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinSida;
    private javax.swing.JButton btnRegistrera;
    private javax.swing.JComboBox<String> jComboBoxValjRas;
    private javax.swing.JLabel lblAnsvarigAgent;
    private javax.swing.JLabel lblEpost;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblPlats;
    private javax.swing.JLabel lblRas;
    private javax.swing.JLabel lblRegDatum;
    private javax.swing.JLabel lblRegistreraAlien;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblVarierande;
    private javax.swing.JTextField txtAnsvAgent;
    private javax.swing.JTextField txtDatumReg;
    private javax.swing.JTextField txtEpostReg;
    private javax.swing.JTextField txtLosenOrdReg;
    private javax.swing.JTextField txtNamnReg;
    private javax.swing.JTextField txtPlatsReg;
    private javax.swing.JTextField txtTelReg;
    private javax.swing.JTextField txtVarierande;
    // End of variables declaration//GEN-END:variables
}
