/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author samsung
 */
public class RegistreraKommunikation extends javax.swing.JPanel {
    private String epost;
    private String isAdmin;
    private static InfDB idb;
    private final String id;

    /**
     * Creates new form RegistreraKommunikation
     */
    public RegistreraKommunikation(String id, String epost, String isAdmin) {
        initComponents();
        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        this.id = id;
        this.epost = epost;
        this.isAdmin = isAdmin;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        tfAngivenOverforingsteknik = new javax.swing.JTextField();
        btnLaggTill = new javax.swing.JButton();

        lblRubrik.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblRubrik.setText("Ange överföringsteknik");

        btnLaggTill.setText("Lägg till");
        btnLaggTill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLaggTillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfAngivenOverforingsteknik)
                    .addComponent(btnLaggTill, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(131, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblRubrik)
                .addGap(18, 18, 18)
                .addComponent(tfAngivenOverforingsteknik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnLaggTill)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLaggTillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLaggTillActionPerformed
        String overforingsTeknik = tfAngivenOverforingsteknik.getText();
        if (ValideringsKlass.validateTextFieldNotEmpty(overforingsTeknik)) {
            try {
                idb.insert("insert into kommunikation values (" + id + ", '" + overforingsTeknik + "')");
                JOptionPane.showMessageDialog(null, "Kommunikation har lagts till!");
                JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(RegistreraKommunikation.this);
                frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
                frame.revalidate();
                frame.setTitle("Startsida: Agent");
                frame.repaint();
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Kommunikationsfel!");
            }
        }
    }//GEN-LAST:event_btnLaggTillActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLaggTill;
    private javax.swing.JLabel lblRubrik;
    private javax.swing.JTextField tfAngivenOverforingsteknik;
    // End of variables declaration//GEN-END:variables
}
