/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;
import java.util.ArrayList;


/**
 *
 * @author ASUS
 */
public class SeDinUtrustningForm extends javax.swing.JPanel {
     private String epost;
     private String isAdmin;
     private static InfDB idb;
     private int agentID;
     private ArrayList<String> allUtrustning;
     private ArrayList<String> vapen;
     private ArrayList<String> teknik;
     private ArrayList<String> kommunikation;
    /**
     * Creates new form SeDinUtrustningForm
     */
    public SeDinUtrustningForm(String epost,String isAdmin) {
        initComponents();
         try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        
        
        this.epost = epost;
        this.isAdmin = isAdmin;
        agentID = getAgentID();
        getAllUtrustning();
        getVapenNamn();
        getTeknikNamn();
        getKommunikationNamn();
       
        fyllVapenComboBox();
        fyllTeknikComboBox();
        fyllKommunikationComboBox();
      
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMinSida = new javax.swing.JButton();
        lblUtrustning = new javax.swing.JLabel();
        jComboVapen = new javax.swing.JComboBox<>();
        jComboTeknik = new javax.swing.JComboBox<>();
        jComboKommunikation = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setFocusTraversalPolicyProvider(true);
        setMaximumSize(new java.awt.Dimension(550, 343));
        setMinimumSize(new java.awt.Dimension(550, 343));

        btnMinSida.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        lblUtrustning.setFont(new java.awt.Font("MS Gothic", 1, 24)); // NOI18N
        lblUtrustning.setText("Din utkvitterade utrustning:");

        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Vapen:");

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Teknik");

        jLabel4.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel4.setText("Kommunikation:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinSida)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(3, 3, 3)))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboTeknik, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboKommunikation, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboVapen, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(lblUtrustning)))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lblUtrustning)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboVapen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jComboTeknik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jComboKommunikation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addComponent(btnMinSida)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
       JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(SeDinUtrustningForm.this);
                frame.setContentPane(new MinSidaAgentForm(epost,isAdmin));
                frame.revalidate();
                frame.setTitle("Startsida: Agent");
                frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed
  
   private int getAgentID() {
       
    String query = "SELECT Agent_ID FROM mibdb.agent WHERE Epost = '" + epost + "'";
    try {
        String agentIDString = idb.fetchSingle(query);
        return Integer.parseInt(agentIDString);
    } catch (InfException ex) {
      
    }
    return -1;
  }
  private void getAllUtrustning() {
    String query = "SELECT Benamning FROM mibdb.utrustning WHERE mibdb.utrustning.Utrustnings_ID IN " +
                   "(SELECT mibdb.innehar_utrustning.Utrustnings_ID FROM mibdb.innehar_utrustning " +
                   "WHERE mibdb.innehar_utrustning.Agent_ID = " + agentID + ")";
    try {
        allUtrustning = idb.fetchColumn(query);
        
    } catch (InfException ex) {
        // Hantera undantag här
        ex.printStackTrace();
    }
    
}
  
  
  
  private void getVapenNamn() {
    String query = "SELECT Benamning FROM mibdb.utrustning WHERE mibdb.utrustning.Utrustnings_ID IN (SELECT Utrustnings_ID FROM mibdb.vapen);";
    try {
        vapen = idb.fetchColumn(query);
    } catch (InfException ex) {
        
        ex.printStackTrace();
    }
}
  
  private void getTeknikNamn()
  {
  String query = "SELECT Benamning FROM mibdb.utrustning WHERE mibdb.utrustning.Utrustnings_ID IN (SELECT Utrustnings_ID FROM mibdb.teknik);";
    try {
        teknik = idb.fetchColumn(query);
    } catch (InfException ex) {
        
        ex.printStackTrace();
    }
  }
  private void getKommunikationNamn()
  {
  String query = "SELECT Benamning FROM mibdb.utrustning WHERE mibdb.utrustning.Utrustnings_ID IN (SELECT Utrustnings_ID FROM mibdb.kommunikation);";
    try {
        kommunikation = idb.fetchColumn(query);
    } catch (InfException ex) {
       
        ex.printStackTrace();
    }
  }
   private void fyllVapenComboBox()
   {
    for(String vapen : vapen)
    {
    if(allUtrustning.contains(vapen))
    {
     jComboVapen.addItem(vapen);
    }
    }
   
   }
   private void fyllTeknikComboBox()
   {
   for(String teknik : teknik)
    {
    if(allUtrustning.contains(teknik))
    {
     jComboTeknik.addItem(teknik);
    }
    }
   
   }
    private void fyllKommunikationComboBox()
   {
   for(String kom : kommunikation)
    {
    if(allUtrustning.contains(kom))
    {
     jComboKommunikation.addItem(kom);
    }
    }
   
   }
    
    public void omIngenUtrustning()
    {
    if(vapen.isEmpty()|| teknik.isEmpty()||kommunikation.isEmpty())
    {
    lblUtrustning.setText("Du har ingen utrustning utkvitterad.");
    }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinSida;
    private javax.swing.JComboBox<String> jComboKommunikation;
    private javax.swing.JComboBox<String> jComboTeknik;
    private javax.swing.JComboBox<String> jComboVapen;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblUtrustning;
    // End of variables declaration//GEN-END:variables
}
