/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;
import javax.swing.JComboBox;

/**
 * Denna sida tar bort utrustning från databasen. Först utförs en kontroll för 
 * att se vilken sorts utrustning det är, och sedan tas den bort både från sin 
 * specifika tabell och huvudtabellen med alla utrustningsID:n.
 * @author samsung
 */
public class TaBortUtrustning extends javax.swing.JPanel {

    private static InfDB idb;
    private String epost;
    private String isAdmin;
    private boolean vapenTryckt;
    private boolean kommTryckt;
    private boolean teknikTryckt;
    

    /**
     * Creates new form TaBortUtrustning
     */
    public TaBortUtrustning(String epost, String isAdmin) {
        initComponents();

        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        this.epost = epost;
        this.isAdmin = isAdmin;
        fyllComboBoxVapen();
        fyllComboBoxKommunikation();
        fyllComboBoxTeknik();
        vapenTryckt = false;
        teknikTryckt = false;
        kommTryckt = false;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        cbVapen = new javax.swing.JComboBox<>();
        btnTaBort = new javax.swing.JButton();
        btnMinSida = new javax.swing.JButton();
        cbTeknik = new javax.swing.JComboBox<>();
        cbKomm = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnTaBort1 = new javax.swing.JButton();
        btnTaBort2 = new javax.swing.JButton();
        btnUtrustning = new javax.swing.JButton();

        lblRubrik.setFont(new java.awt.Font("MS Gothic", 1, 18)); // NOI18N
        lblRubrik.setText("Ta bort utrustning:");

        cbVapen.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj vapen" }));

        btnTaBort.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        btnMinSida.setBackground(new java.awt.Color(242, 242, 242));
        btnMinSida.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        cbTeknik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj teknik" }));

        cbKomm.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj kommunikation" }));

        jLabel1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Vapen:");

        jLabel2.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Teknik:");

        jLabel3.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Kommunikation:");

        btnTaBort1.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnTaBort1.setText("Ta bort");
        btnTaBort1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBort1ActionPerformed(evt);
            }
        });

        btnTaBort2.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnTaBort2.setText("Ta bort");
        btnTaBort2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBort2ActionPerformed(evt);
            }
        });

        btnUtrustning.setBackground(new java.awt.Color(242, 242, 242));
        btnUtrustning.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnUtrustning.setText("Utrustning");
        btnUtrustning.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUtrustningActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnMinSida)
                        .addGap(38, 38, 38))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRubrik)
                        .addGap(169, 169, 169))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbVapen, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(cbTeknik, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(cbKomm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnUtrustning)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnTaBort)
                                .addGap(83, 83, 83)
                                .addComponent(btnTaBort1)
                                .addGap(67, 67, 67)
                                .addComponent(btnTaBort2)))))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblRubrik)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbTeknik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbVapen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbKomm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTaBort1)
                    .addComponent(btnTaBort2)
                    .addComponent(btnTaBort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMinSida)
                    .addComponent(btnUtrustning))
                .addGap(26, 26, 26))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        vapenTryckt = true;
        taBort(cbVapen);
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(TaBortUtrustning.this);
        frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Startsida: Agent");
        frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed

    private void btnTaBort1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBort1ActionPerformed
        teknikTryckt = true;
        taBort(cbTeknik);
    }//GEN-LAST:event_btnTaBort1ActionPerformed

    private void btnTaBort2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBort2ActionPerformed
        kommTryckt = true;
        taBort(cbKomm);
    }//GEN-LAST:event_btnTaBort2ActionPerformed

    private void btnUtrustningActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUtrustningActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(TaBortUtrustning.this);
        frame.setContentPane(new HanteraUtrustningForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Hantera utrustning");
        frame.repaint();
    }//GEN-LAST:event_btnUtrustningActionPerformed

    private void fyllComboBoxVapen() {
        cbVapen.removeAllItems();
        cbVapen.addItem("Välj utrustning");
        try {
           ArrayList<String> utrustningsBenamningar = idb.fetchColumn("SELECT benamning FROM utrustning WHERE Utrustnings_ID IN (SELECT Utrustnings_ID FROM vapen)");
            for (String enBenamning : utrustningsBenamningar) {
                cbVapen.addItem(enBenamning);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");

        }
    }
    private void fyllComboBoxTeknik() {
        cbTeknik.removeAllItems();
        cbTeknik.addItem("Välj utrustning");
        try {
           ArrayList<String> utrustningsBenamningar = idb.fetchColumn("SELECT benamning FROM utrustning WHERE Utrustnings_ID IN (SELECT Utrustnings_ID FROM teknik)");
            for (String enBenamning : utrustningsBenamningar) {
                cbTeknik.addItem(enBenamning);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");

        }
    }
    private void fyllComboBoxKommunikation() {
        cbKomm.removeAllItems();
        cbKomm.addItem("Välj utrustning");
        try {
           ArrayList<String> utrustningsBenamningar = idb.fetchColumn("SELECT benamning FROM utrustning WHERE Utrustnings_ID IN (SELECT Utrustnings_ID FROM kommunikation)");
            for (String enBenamning : utrustningsBenamningar) {
                cbKomm.addItem(enBenamning);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");

        }
    }

 private void taBortFranUtrustningsTyp(String valtUtrustningsID) {
    if (kommTryckt) {
        try {
            idb.delete("delete from kommunikation where utrustnings_id = " + valtUtrustningsID);
            kommTryckt = false;
            fyllComboBoxKommunikation();
        } catch (InfException ex) {
             JOptionPane.showMessageDialog(null, "Ett fel uppstod vid borttagning från av kommunikationsutrustning.");
            
        }
    }
        
    try {
        if (vapenTryckt) {
            idb.delete("delete from vapen where utrustnings_id = " + valtUtrustningsID);
            vapenTryckt = false;
            fyllComboBoxVapen();
        }
    } catch (InfException ex2) {
         JOptionPane.showMessageDialog(null, "Ett fel uppstod vid borttagning av vapen.");
        
    }
            
    try {
        if (teknikTryckt) {
            idb.delete("delete from teknik where utrustnings_id = " + valtUtrustningsID);
            teknikTryckt = false;
            fyllComboBoxTeknik();
        }
    } catch (InfException ex3) {
         JOptionPane.showMessageDialog(null, "Ett fel uppstod vid borttagning av teknik");
        
    }
}
  private void taBort(JComboBox box)
  {
  String valdUtrustning = box.getSelectedItem().toString();
        try {
            String valtUtrustningsID = idb.fetchSingle("select utrustnings_id from utrustning where benamning = '" + valdUtrustning + "'");
            taBortFranUtrustningsTyp(valtUtrustningsID);

            idb.delete("delete from innehar_utrustning where utrustnings_id = " + valtUtrustningsID);
            idb.delete("delete from utrustning where utrustnings_id = " + valtUtrustningsID);

            JOptionPane.showMessageDialog(null, "Utrustningen har tagits bort!");
            fyllComboBoxVapen();

        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");

        }
  
  }
  
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinSida;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JButton btnTaBort1;
    private javax.swing.JButton btnTaBort2;
    private javax.swing.JButton btnUtrustning;
    private javax.swing.JComboBox<String> cbKomm;
    private javax.swing.JComboBox<String> cbTeknik;
    private javax.swing.JComboBox<String> cbVapen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblRubrik;
    // End of variables declaration//GEN-END:variables
}
