/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package mib.p;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author samsung
 */
public class TaBortUtrustning extends javax.swing.JPanel {
    private static InfDB idb;
    private String epost;
    private String isAdmin;

    /**
     * Creates new form TaBortUtrustning
     */
    public TaBortUtrustning(String epost, String isAdmin) {
        initComponents();
        

        try {
            idb = new InfDB("mibdb", "3306", "mibdba", "mibkey");
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
            System.out.println("Internt felmeddelande" + ex.getMessage());
        }
        this.epost = epost;
        this.isAdmin = isAdmin;
        fyllComboBox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();
        cbValjUtrustning = new javax.swing.JComboBox<>();
        btnTaBort = new javax.swing.JButton();
        btnMinSida = new javax.swing.JButton();

        lblRubrik.setFont(new java.awt.Font("MS Gothic", 1, 12)); // NOI18N
        lblRubrik.setText("Ta bort utrustning:");

        btnTaBort.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnTaBort.setText("Ta bort");
        btnTaBort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaBortActionPerformed(evt);
            }
        });

        btnMinSida.setFont(new java.awt.Font("MS Gothic", 1, 14)); // NOI18N
        btnMinSida.setText("Min sida");
        btnMinSida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinSidaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(186, 186, 186)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblRubrik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbValjUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnTaBort)))
                .addContainerGap(231, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinSida)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(lblRubrik)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbValjUtrustning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnTaBort)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                .addComponent(btnMinSida)
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaBortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaBortActionPerformed
        String valdUtrustning = cbValjUtrustning.getSelectedItem().toString();
        try {
            String valtUtrustningsID = idb.fetchSingle("select utrustnings_id from utrustning where benamning = '" + valdUtrustning + "'");
            idb.delete("delete from utrustning where utrustnings_id = " + valtUtrustningsID);
            idb.delete("delete from innehar_utrustning where utrustnings_id = " + valtUtrustningsID);
            taBortFranUtrustningsTyp(valtUtrustningsID);
            JOptionPane.showMessageDialog(null, "Utrustningen har tagits bort!");
            
            JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(TaBortUtrustning.this);
            frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
            frame.revalidate();
            frame.setTitle("Startsida: Agent");
            frame.repaint();
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }//GEN-LAST:event_btnTaBortActionPerformed

    private void btnMinSidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinSidaActionPerformed
        JFrame frame = (JFrame) SwingUtilities.getWindowAncestor(TaBortUtrustning.this);
        frame.setContentPane(new MinSidaAgentForm(epost, isAdmin));
        frame.revalidate();
        frame.setTitle("Startsida: Agent");
        frame.repaint();
    }//GEN-LAST:event_btnMinSidaActionPerformed

    private void fyllComboBox() {
        cbValjUtrustning.removeAllItems();
        try {
            ArrayList<String> utrustningsBenamningar = idb.fetchColumn("select benamning from utrustning");
            for (String enBenamning : utrustningsBenamningar) {
                cbValjUtrustning.addItem(enBenamning);
            }
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }
    
    private void taBortFranUtrustningsTyp(String valtUtrustningsID) {
        try {
            idb.delete("delete from vapen where utrustnings_id = " + valtUtrustningsID);
            idb.delete("delete from kommunikation where utrustnings_id = " + valtUtrustningsID);
            idb.delete("delete from teknik where utrustnings_id = " + valtUtrustningsID);
        } catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Något gick fel!");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinSida;
    private javax.swing.JButton btnTaBort;
    private javax.swing.JComboBox<String> cbValjUtrustning;
    private javax.swing.JLabel lblRubrik;
    // End of variables declaration//GEN-END:variables
}
